<?php

/**
 * ModelContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ModelContact extends PluginModelContact
{
  const MODEL_DEPARTMENTS = 'departments';
  const MODEL_ORGANIZATION = 'organization';
}