<?php

/**
 * BaseWidgetListPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $widget_id
 * @property integer $permission_id
 * @property WidgetList $WidgetList
 * @property sfGuardPermission $Permission
 * 
 * @method integer              getWidgetId()      Returns the current record's "widget_id" value
 * @method integer              getPermissionId()  Returns the current record's "permission_id" value
 * @method WidgetList           getWidgetList()    Returns the current record's "WidgetList" value
 * @method sfGuardPermission    getPermission()    Returns the current record's "Permission" value
 * @method WidgetListPermission setWidgetId()      Sets the current record's "widget_id" value
 * @method WidgetListPermission setPermissionId()  Sets the current record's "permission_id" value
 * @method WidgetListPermission setWidgetList()    Sets the current record's "WidgetList" value
 * @method WidgetListPermission setPermission()    Sets the current record's "Permission" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWidgetListPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('widget_list_permission');
        $this->hasColumn('widget_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WidgetList', array(
             'local' => 'widget_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}