<?php

/**
 * BaseDocDocumentGroupSfUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sfguarduser_id
 * @property integer $docdocumentgroup_id
 * @property enum $actionkey
 * @property sfGuardUser $sfUsers
 * @property DocDocumentGroup $DocGroups
 * 
 * @method integer                 getSfguarduserId()       Returns the current record's "sfguarduser_id" value
 * @method integer                 getDocdocumentgroupId()  Returns the current record's "docdocumentgroup_id" value
 * @method enum                    getActionkey()           Returns the current record's "actionkey" value
 * @method sfGuardUser             getSfUsers()             Returns the current record's "sfUsers" value
 * @method DocDocumentGroup        getDocGroups()           Returns the current record's "DocGroups" value
 * @method DocDocumentGroupSfUsers setSfguarduserId()       Sets the current record's "sfguarduser_id" value
 * @method DocDocumentGroupSfUsers setDocdocumentgroupId()  Sets the current record's "docdocumentgroup_id" value
 * @method DocDocumentGroupSfUsers setActionkey()           Sets the current record's "actionkey" value
 * @method DocDocumentGroupSfUsers setSfUsers()             Sets the current record's "sfUsers" value
 * @method DocDocumentGroupSfUsers setDocGroups()           Sets the current record's "DocGroups" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocDocumentGroupSfUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doc_document_group_sf_users');
        $this->hasColumn('sfguarduser_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('docdocumentgroup_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('actionkey', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'action_show',
              1 => 'action_edit',
              2 => 'action_all',
             ),
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as sfUsers', array(
             'local' => 'sfguarduser_id',
             'foreign' => 'id'));

        $this->hasOne('DocDocumentGroup as DocGroups', array(
             'local' => 'docdocumentgroup_id',
             'foreign' => 'id'));
    }
}