<?php

/**
 * BaseDocDocumentGroupSfGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sfguardgroup_id
 * @property integer $docdocumentgroup_id
 * @property enum $actionkey
 * @property sfGuardGroup $sfGroups
 * @property DocDocumentGroup $DocGroups
 * 
 * @method integer                  getSfguardgroupId()      Returns the current record's "sfguardgroup_id" value
 * @method integer                  getDocdocumentgroupId()  Returns the current record's "docdocumentgroup_id" value
 * @method enum                     getActionkey()           Returns the current record's "actionkey" value
 * @method sfGuardGroup             getSfGroups()            Returns the current record's "sfGroups" value
 * @method DocDocumentGroup         getDocGroups()           Returns the current record's "DocGroups" value
 * @method DocDocumentGroupSfGroups setSfguardgroupId()      Sets the current record's "sfguardgroup_id" value
 * @method DocDocumentGroupSfGroups setDocdocumentgroupId()  Sets the current record's "docdocumentgroup_id" value
 * @method DocDocumentGroupSfGroups setActionkey()           Sets the current record's "actionkey" value
 * @method DocDocumentGroupSfGroups setSfGroups()            Sets the current record's "sfGroups" value
 * @method DocDocumentGroupSfGroups setDocGroups()           Sets the current record's "DocGroups" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocDocumentGroupSfGroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doc_document_group_sf_groups');
        $this->hasColumn('sfguardgroup_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('docdocumentgroup_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('actionkey', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'action_show',
              1 => 'action_edit',
              2 => 'action_all',
             ),
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup as sfGroups', array(
             'local' => 'sfguardgroup_id',
             'foreign' => 'id'));

        $this->hasOne('DocDocumentGroup as DocGroups', array(
             'local' => 'docdocumentgroup_id',
             'foreign' => 'id'));
    }
}