<?php

/**
 * WidgetListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WidgetListTable extends PluginWidgetListTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WidgetListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WidgetList');
    }
}