<?php

/**
 * WidgetListPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WidgetListPermissionTable extends PluginWidgetListPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WidgetListPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WidgetListPermission');
    }
}