<?php

/**
 * DocDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DocDocument extends PluginDocDocument
{
   public function save(Doctrine_Connection $conn = null)
   {
       parent::save();
       LogIntranet::SaveLog($this);
   }
   public function delete(Doctrine_Connection $conn = null)
   {
       $this->setIsdeleted(true);
       parent::save();
       LogIntranet::SaveLog($this);
   }

  public function hardDelete(Doctrine_Connection $conn = null)
  {
    parent::delete();
  }

   public function restore(Doctrine_Connection $conn = null)
   {
       $this->setIsdeleted(false);
       parent::save();
       LogIntranet::SaveLog($this);
   }
   
   public function getLastVersion()
   {
       $versions = doctrine::getTable('DocDocumentVersion')
       ->createQuery('dv')
       ->where('dv.document_id ='.$this->getId())
       ->orderBy('dv.id DESC')
       ->execute();
       if (count($versions))
       {
           $last_version = $versions->getFirst();
       } else $last_version = null;
       return $last_version; 
   }
   
   
}