<?php

/**
 * DocDocumentGroupSfUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocDocumentGroupSfUsersTable extends PluginDocDocumentGroupSfUsersTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocDocumentGroupSfUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocDocumentGroupSfUsers');
    }
}