<?php

/**
 * DocDocumentGroupSfGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DocDocumentGroupSfGroups extends PluginDocDocumentGroupSfGroups
{
    static function isExist($groupid, $parentid, $actionkey)
    {
       $q = Doctrine::getTable('DocDocumentGroupSfGroups')
       ->createQuery('c')
       ->where('sfguardgroup_id ='.$groupid)
       ->andWhere('docdocumentgroup_id ='.$parentid)
       ->andWhere('actionkey = \''.$actionkey.'\'')
       ->execute();
       return count($q);
       
    }
}