<?php

/**
 * LogIntranet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LogIntranet extends PluginLogIntranet
{
   static function SaveLog(Doctrine_Record $obj)
   {
     $sf_context =  sfContext::getInstance();
     $user_id = $sf_context->getUser()->getAttribute('user_id', null, 'sfGuardSecurityUser');
     $logkey =  $sf_context->getActionName();
     $log_object = new LogIntranet();
     $log_object->setUserId($user_id);  
     $log_object->setObjId($obj->getId());  
     $log_object->setDescription($obj->getTable()->getOption('tableName'));
     $log_object->setCreatedatetime(date("Y-m-d H:i:s"));  
     $log_object->setLogkey($logkey);  
     $log_object->setLogtype($obj->getTable()->getOption('name'));
     $log_object->save();  
   }
}