generator:
  class: sfDoctrineGenerator
  param:
    model_class:           District
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          district
    with_doctrine_route:   true
    actions_base_class:    sfActions

    
    
    
    config:
      actions: ~
      fields:  ~
      list:    
        display: [name, region, population, square, density]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
