<?php

/**
 * HandlingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingTable extends PluginHandlingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Handling');
    }

  /**
   * get organization form crm
   */
  static public function getMyHandlingQuery()
  {
    $query = self::getInstance()
      ->createQuery('h')
      ->leftJoin('h.HandlingUser hu')
      ->leftJoin('h.Result hr')
      ->leftJoin('hu.User manager')
      ->leftJoin('h.Status status')
      ->leftJoin('h.Organization o')
      ->leftJoin('h.User users')
      ->leftJoin('o.Scope scope')
      ->leftJoin('o.City cit');


    $user = sfContext::getInstance()->getUser();

    if (!$user->hasCredential('crmadmin'))
    {
      $userId = $user->getId();

      $query
        ->leftJoin('o.OrganizationUser ou')
        ->addWhere('(ou.user_id = ? OR hu.user_id = ?)', array($userId, $userId));
        //->orWhere('hu.user_id = ?', $userId);
    }

    $query
      ->orderBy('h.id DESC');

    return $query;
  }
}