<?php

/**
 * HandlingMoreInfoTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingMoreInfoTypeTable extends PluginHandlingMoreInfoTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingMoreInfoTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HandlingMoreInfoType');
    }
}