<?php

/**
 * HandlingMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HandlingMessage extends PluginHandlingMessage
{
  public function getCreatedatetimeGood()
  {
    return format_date($this->getCreatedatetime(), 'dd.MM.yyyy, HH:mm', 'ru');
  }

  public function getCreatedateGood()
  {
    return format_date($this->getCreatedate(), 'dd.MM.yyyy', 'ru');
  }

  public function getDescriptionDecoded()
  {
    return html_entity_decode($this->getDescription());
  }

  public function History($field = null, $toString  = null, $oldValue = null)
  {
    if (!$field||!$toString) return null;

    /*if (!sizeof($this->_oldValues))
    {
      return;
    }*/
    $history = new History();

    $history->setModelName(History::MODEL_HANDLING);
    $history->setModelId($this->getHandlingId());
    $history->setFieldName('handling_message_'.$field);

    //$history->setMore();

    $history->setOldValue($oldValue ?  $oldValue : $this->$toString());
    $history->setValue($this->$toString());
    $history->save();
  }

  public function getHandlingMessageTypeString()
  {
    return ''.$this->getHandlingMessageType();
  }
}
