<?php

/**
 * HandlingResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HandlingResult extends PluginHandlingResult
{
  const TYPE_LOST = 'lost';
  const TYPE_COMPETITOR = 'competitor';
  const TYPE_POSTPONED= 'postponed';

  static public function getIdBySlug($slug)
  {
    $query = Doctrine::getTable('HandlingResult')
      ->createQuery('hr')
      ->where('hr.slug = ?', $slug)
      ->fetchOne();

    return $query ? $query->getId() : null;
  }

  static public function getSlugById($id)
  {
    $query = Doctrine::getTable('HandlingResult')
      ->createQuery('hr')
      ->where('hr.id = ?', $id)
      ->fetchOne();

    return $query ? $query->getSlug() : null;
  }
}
