<?php

/**
 * HandlingUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingUserTable extends PluginHandlingUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HandlingUser');
    }
}