<?php

/**
 * HandlingMoreInfoType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HandlingMoreInfoType extends PluginHandlingMoreInfoType
{
  static public function getTypesByResultId($resultId)
  {
    return Doctrine::getTable('HandlingMoreInfoType')
      ->createQuery('hmit')
      ->where('hmit.handling_result_id = ?', $resultId)
      ->orderBy('hmit.id ASC')
      ->execute();
  }
}
