<?php

/**
 * HandlingMoreInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HandlingMoreInfo extends PluginHandlingMoreInfo
{
  static public function getFormattedData($handlingId)
  {
    $query = Doctrine::getTable('HandlingMoreInfo')
      ->createQuery('hmi')
      ->where('hmi.handling_id = ?', $handlingId)
      ->execute();

    if (!sizeof($query))
    {
      return array();
    }

    return $query->toKeyValueArray('handling_more_info_type_id', 'itself');
  }

  public function getItself()
  {
    return $this;
  }

  static public function getAllFormattedData()
  {
    $query = Doctrine::getTable('HandlingMoreInfo')
      ->createQuery('hmi')
      ->execute();

    if (!sizeof($query))
    {
      return array();
    }

    $result = array();

    foreach ($query as $item)
    {
      if (!isset($result[$item->getHandlingId()]))
      {
        $result[$item->getHandlingId()] = array();
      }

      $result[$item->getHandlingId()][$item->getHandlingMoreInfoTypeId()] = $item->getValue();
    }

    return $result;
  }
}
