<?php

/**
 * HandlingTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingTypeTable extends PluginHandlingTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HandlingType');
    }
}