<?php

/**
 * HandlingMoreInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingMoreInfoTable extends PluginHandlingMoreInfoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingMoreInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HandlingMoreInfo');
    }
}