<?php

/**
 * HandlingMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingMessageTable extends PluginHandlingMessageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HandlingMessage');
    }
}