<?php

/**
 * HandlingStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HandlingStatusTable extends PluginHandlingStatusTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HandlingStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HandlingStatus');
    }
}