default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, style.css, main.css, jquery-ui.css]

  javascripts:    [jquery.min.js, jquery.ui.min.js, jquery.dataTables.js, FixedHeader.min.js]

  has_layout:     true
  layout:         layout