<?php

/**
 * PluginTenderkeywordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTenderkeywordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTenderkeywordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTenderkeywords');
    }
}