<?php

/**
 * PluginTendercategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTendercategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTendercategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTendercategory');
    }
}