<?php

/**
 * claim_worksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class claim_worksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object claim_worksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('claim_works');
    }
}