<?php

/**
 * client_departmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class client_departmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object client_departmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('client_departments');
    }
}