<?php

/**
 * companystructureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class companystructureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object companystructureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('companystructure');
    }

    public function getTreeChoices()
    {
      $query = Doctrine::getTable('companystructure')
        ->createQuery('cs')
        ->execute();

      $root = array();
      $result = array('' => '');

      foreach($query as $item)
      {
        if (!$item->getParentId())
        {
          $root[$item->getId()] = $item->getName();
        }
      }

      foreach ($root as $rootKey => $rootValue)
      {
        $result[$rootKey] = $rootValue;

        foreach($query as $item)
        {
          if ($item->getParentId() == $rootKey)
          {
            $result[$item->getId()] = $item->getTreeElement();
          }
        }
      }

      return $result;
    }

}