<?php

/**
 * contractTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class contractTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object contractTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('contract');
    }
    
  static public function getContractIdByOrganizationId($organization_id)
  {
    $contract = Doctrine::getTable('contract')
      ->createQuery('c')
      ->where('organization_id = ?', $organization_id)
      ->fetchOne();
    
    return $contract ? $contract->getId() : null;
      
  }
}