<?php

/**
 * contract_importance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class contract_importance extends Basecontract_importance
{
    public function __toString()
    {
        return $this->getImportance()->getName();
    }
    
    public function getOrganizationId()
   {
       return $this->getContract()->getOrganization()->getId();
   }    
    

}

