<?php

/**
 * DepartmentsTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentsTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartmentsTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DepartmentsType');
    }
}