<?php

/**
 * DepartmentPeopleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentPeopleTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object DepartmentPeopleTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('DepartmentPeople');
  }

  static public function getPeople($departmentIds, $year, $month, $departmentPeopleId = null, $departmentPeopleReplacementId = null)
  {
    $peopleIds = GrafikTable::getPeopleIds($departmentIds, $year, $month, $departmentPeopleId, $departmentPeopleReplacementId);

    if (!sizeof($peopleIds))
    {
      return array();
    }

    return self::getPeopleByIds($peopleIds, $year, $month, $departmentPeopleId, $departmentPeopleReplacementId);
  }

  static public function getPeopleByIds($peopleIds, $year, $month, $departmentPeopleId = null, $departmentPeopleReplacementId = null, $replacementType = '')
  {
    if (!sizeof($peopleIds))
    {
      return array();
    }

    $individualIds = DepartmentPeopleTable::getIndividualIds($peopleIds);

    /** @var Doctrine_Collection $query */
    $query = self::getInstance()
      ->createQuery('dp')
      //->leftJoin('dp.Position as position')
      ->whereIn('dp.id', $peopleIds)
      ->orderBy('dp.id ASC')
      ->execute();

    if (!sizeof($query))
    {
      return array();
    }

    $individuals = array();

    if (sizeof($individualIds))
    {
      $individuals = Doctrine::getTable('Individual')
        ->createQuery('i')
        ->whereIn('id', $individualIds)
        ->execute();

      if (sizeof($individuals))
      {
        $individuals = $individuals->toKeyValueArray('id', 'itself');
      }
    }

    /** @var Doctrine_Collection $monthInfoCollection */
    $queryMonth = Doctrine::getTable('DepartmentPeopleMonthInfo')
      ->createQuery('dpmi')
      ->whereIn('dpmi.department_people_id', $peopleIds)
      ->addWhere('dpmi.year = ? ', $year)
      ->addWhere('dpmi.month = ? ', $month)
      ->leftJoin('dpmi.DepartmentPeople dp')
      ->orderBy('dp.last_name ASC');

    if (!is_null($departmentPeopleReplacementId))
    {
      $queryMonth
        ->addWhere('dpmi.department_people_replacement_id = ?', $departmentPeopleReplacementId);
    }

    if ($replacementType)
    {
      $queryMonth
        ->addWhere('dpmi.replacement_type = ?', $replacementType);
    }

    $monthInfoCollection = $queryMonth->execute();

    if (!sizeof($monthInfoCollection))
    {
      return array();
    }

    $result = array();

    $peopleArray = $query->toKeyValueArray('id', 'itself');

    foreach ($monthInfoCollection as $info) /** @var DepartmentPeopleMonthInfo $info */
    {
      $personId = $info->getDepartmentPeopleId();
      $year = $info->getYear();
      $month = $info->getMonth();
      $replacementId = $info->getDepartmentPeopleReplacementId();
      $replacementType = $info->getReplacementType();

      if (!isset($peopleArray[$personId]))
      {
        continue;
      }

      /** @var DepartmentPeople $person */
      $person = clone $peopleArray[$personId];

      $person->setYearMonthReplacement($year, $month, $replacementId, $replacementType);

      if (isset($individuals[$person->getIndividualId()]))
      {
        $person->setIndividualInfo($individuals[$person->getIndividualId()]);
      }

      $result[] = $person;
    }

    return $result;
  }

  /**
   * Get all people for $departmentIds in array with departmentId key
   *
   * @param int|int[] $departmentIds
   * @param int $year
   * @param int $month
   * @return mixed[]
   */
  static public function getPeopleArrayByDepartmentIdKey($departmentIds, $year, $month)
  {
    $people = self::getPeople($departmentIds, $year, $month);

    $result = array();

    foreach($people as $person)
    {
      if (!isset($result[$person->getDepartmentId()]))
      {
        $result[$person->getDepartmentId()] = array();
      }

      $result[$person->getDepartmentId()][] = $person;
    }

    return $result;
  }

  /**
   * Get individuals ids depending on $departmentPeopleIds
   *
   * @param int[] departmentPeopleIds
   *
   * @return int[]
   */
  public static function getIndividualIds($departmentPeopleIds)
  {
    $query = Doctrine::getTable('DepartmentPeople')
      ->createQuery('dp')
      ->select('DISTINCT(dp.individual_id) AS individual_id')
      ->whereIn('dp.id', $departmentPeopleIds)
      ->andWhere('dp.individual_id IS NOT NULL');

    $individuals = $query->fetchArray();

    $result = array();

    foreach ($individuals as $individual)
    {
      $result[$individual['individual_id']] = $individual['individual_id'];
    }

    return $result;
  }

  public static function getSearchResultsAutocomplite($s, $mpkId, $departmentId)
  {
    $pattern = $s;

    $mpk = Doctrine::getTable('mpk')->findOneBy('name', $mpkId);

    $departmentId = $mpk ? $mpk->getDepartmentId() : $departmentId;

    $q = Doctrine::getTable('DepartmentPeople')
      ->createQuery('dp')
      ->select('dp.id as id')
      ->addSelect('i.last_name as last_name')
      ->addSelect('i.middle_name as middle_name')
      ->addSelect('i.first_name as first_name')
      ->leftJoin('dp.Individual i')
      ->where('LOWER(i.last_name) LIKE ?', '%'.strtolower($pattern)."%")
      ->andWhere('dp.department_id = ?', $departmentId);

    $q = $q->fetchArray();

    $result = array();
    foreach ($q as $object)
    {
      $result[$object['id']] = $object['last_name'] . ' ' . $object['first_name'] . ' ' . $object['middle_name'];;
    }

    return $result;
  }
}