<?php

/**
 * DocumentstypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentstypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentstypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documentstype');
    }
}