<?php

/**
 * DocumentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documents');
    }
    
    public function getAllDocumetsByClaim($claim_id)
    {
        return Doctrine::getTable('Documents')
        ->createQuery('d')
        ->leftJoin('d.DocumentsClaim dc')
        ->where('dc.claim_id = '.$claim_id)
        ->execute();
    }
}