<?php

/**
 * DogovorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DogovorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DogovorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dogovor');
    }
    
    public function getAllDogovors()
    {
      return self::getInstance()
        ->createQuery('d')
        ->leftJoin('d.User usr')
        ->leftJoin('d.Stuff stf')
        ->leftJoin('d.Organization org')
        ->leftJoin('d.DogovorType dt')
        ->leftJoin('d.CompanyRole CompanyRole')
        ->leftJoin('d.City cit')
        ->leftJoin('d.Companystructure cstr')
        //->leftJoin('d.Stuff')
        ->execute();
    }

  public function getAllActiveDogovors()
  {
    return self::getInstance()
      ->createQuery('d')
      ->leftJoin('d.User usr')
      ->leftJoin('d.Stuff stf')
      ->leftJoin('d.Organization org')
      ->leftJoin('d.DogovorType dt')
      ->leftJoin('d.CompanyRole CompanyRole')
      ->leftJoin('d.City cit')
      ->leftJoin('d.Companystructure cstr')
      ->where('d.is_active = ?', true)
      //->leftJoin('d.Stuff')
      ->execute();
  }


  public function getProlongationDogovors()
  {
    return self::getInstance()
      ->createQuery('d')
      ->leftJoin('d.User usr')
      ->leftJoin('d.Stuff stf')
      ->leftJoin('d.Organization org')
      ->leftJoin('d.DogovorType dt')
      ->leftJoin('d.CompanyRole CompanyRole')
      ->leftJoin('d.City cit')
      ->leftJoin('d.Companystructure cstr')
      ->where('d.prolongation = ?', true)
      ->addWhere('d.stopdatetime < ?', date('Y-m-d'))
      //->limit(10)
      ->execute();
  }

    public function getDogovorsByIds($ids)
    {
      if (!sizeof($ids))
      {
        return array();
      }
      
      return self::getInstance()
        ->createQuery('d')
        ->whereIn('id', $ids)
        ->leftJoin('d.User usr')
        ->leftJoin('d.Stuff stf')
        ->leftJoin('d.Organization org')
        ->leftJoin('d.DogovorType dt')
        ->leftJoin('d.City cit')
        ->leftJoin('d.Companystructure cstr')
        //->leftJoin('d.Stuff')
        ->execute();
    }
}