<?php

/**
 * DogovorHandlingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DogovorHandlingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DogovorHandlingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DogovorHandling');
    }
}