<?php

/**
 * DogovorDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DogovorDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DogovorDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DogovorDepartment');
    }
    
    static public function getAllDepartments($dogovor_id)
    {
      $q = self::getInstance()
        ->createQuery('dd')
        ->where('dd.dogovor_id = ?', $dogovor_id)
        ->orderBy('dd.id DESC')
        ->execute();
        
      return $q;
    }
}