<?php

/**
 * DopDogovor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DopDogovor extends BaseDopDogovor
{
  public function __toString()
  {
    return "ID".$this->getId()." #".$this->getNumber();
  }
  
  public function canBeDeleted()
  {
    $dogovorId = $this->getDogovorId();
    $dopDogovorId = $this->getId();
    
    $result = Doctrine::getTable('DogovorDepartment')
      ->createQuery('dd')
      ->select('dd.id')
      ->where('dd.dogovor_id = ?', $dogovorId)
      ->addWhere('dd.dop_dogovor_id = ?', $dopDogovorId)
      ->fetchArray();
    
    return !sizeof($result);
  }
  
  public function delete(Doctrine_Connection $conn = null)
  {
    if ($this->canBeDeleted())
    {
      parent::delete();
    }
  }
}