<?php

/**
 * DopDogovorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DopDogovorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DopDogovorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DopDogovor');
    } 
    
    public function getDopDogovorsByDogovorIdQuery($dogovor_id)
    {
      return self::getInstance()
        ->createQuery('d')
        ->where('d.dogovor_id =?', $dogovor_id)
        ->orderBy('d.id DESC');
    }
    
    public function getDopDogovorsByDogovorId($dogovor_id)
    {
      return self::getDopDogovorsByDogovorIdQuery($dogovor_id)
        ->execute();
    }
    
    public function getDopDogovorsByIds($ids)
    {
      if (!sizeof($ids))
      {
        return array();
      }
      
      return self::getInstance()
        ->createQuery('d')
        ->whereIn('id', $ids) 
        ->orderBy('d.id DESC')
        ->execute();
    }
}