<?php

/**
 * FcCostsntypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FcCostsntypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FcCostsntypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FcCostsntypes');
    }
}