<?php

/**
 * FcCostsnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FcCostsnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FcCostsnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FcCostsn');
    }
    
    public function getFcCostsnByFinanceId($finance_claim_id)
    {
        return Doctrine::getTable('FcCostsn')
        ->createQuery('fc')
        ->where('finance_claim_id = '.$finance_claim_id)
        ->execute();
    }
}