<?php

/**
 * finance_claimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class finance_claimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object finance_claimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('finance_claim');
    }
    public function getFinanceClaimByClaimId($claim_id)
    {
        if (!$claim_id) return null;
        $q = Doctrine::getTable('finance_claim')
        ->createQuery('fc')
        ->where('claim_id = '.$claim_id)
        ->execute();
        if (!count($q)){
            $nds = Doctrine::getTable('lookup')->getNds();
            $obnal = Doctrine::getTable('lookup')->getObnal();
            $finance_claim = new finance_claim();
            $finance_claim ->setClaimId($claim_id);
            $finance_claim ->setNds($nds);
            $finance_claim ->setObnal($obnal);
            $finance_claim->save();
            $new_log_claim = new log_claim();
            $user_id = sfContext::getInstance()->getUser()->getAttribute('user_id',null, 'sfGuardSecurityUser');
            $new_log_claim->NewLogRecord($claim_id, $user_id, 'Финансовые показатели созданы',sfConfig::get('logcliam_finance')); 
            $new_log_claim->NewLogRecord($claim_id, $user_id, 'Добавлены значения НДС = '.$nds.', Коэф = '.$obnal,sfConfig::get('logcliam_finance')); 
            return $finance_claim;
        } else return $q->getFirst();
    }
}