<?php

/**
 * GroupclaimClaim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GroupclaimClaim extends BaseGroupclaimClaim
{
      public static function saveAssociation($groupclaim_id = null , $claim_id = null)
      {
         if (!$groupclaim_id||!$claim_id) return false;
         $groupclaim_claim = new GroupclaimClaim();
         $groupclaim_claim->setGroupclaimId($groupclaim_id);
         $groupclaim_claim->setClaimId($claim_id);
         $groupclaim_claim->setCreatedatetime(date("Y-m-d H:i:s"));
         $groupclaim_claim->trySave(); 
      }
}