<?php

/**
 * GroupclaimworkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupclaimworkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupclaimworkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Groupclaimwork');
    }
}