<?php

/**
 * Groupclaimperiod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Groupclaimperiod extends BaseGroupclaimperiod
{
    public function __toString()
    {
        $choises_day =  GroupclaimperiodForm::getChoicesDay();
        $choises_month =  GroupclaimperiodForm::getChoicesMonth();
        $choises_year = GroupclaimperiodForm::getChoicesYear();
        return $choises_day[$this->getPeriodDay()]." - ".$choises_month[$this->getPeriodMonth()]." - ".$choises_year[$this->getPeriodYear()];
    }
}