<?php

/**
 * GroupclaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupclaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupclaimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Groupclaim');
    }
    
    public function getAllGroupclaims()
    {
        return Doctrine::getTable('Groupclaim')
        ->createQuery('c')
        ->execute();
    }
    
    public function getCurrentsGroupclaims()
    {
      $q = Doctrine::getTable('Groupclaim')
      ->createQuery('g')
      ->where('g.is_deleted is false')
      ->orderBy('g.id DESC')
      ->execute();
      return $q;
    }
    
    
}