<?php

/**
 * GroupclaimClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupclaimClaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupclaimClaimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupclaimClaim');
    }
}