<?php

/**
 * IndividualTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndividualTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndividualTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Individual');
    }
}