<?php

/**
 * log_claimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class log_claimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object log_claimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('log_claim');
    }
    
    public function getAllLogClaim()
    {
      return Doctrine_Core::getTable('log_claim')
      ->createQuery('lc')
      ->leftJoin('lc.Users u')
      //->addWhere('c.id = '.$claim_id)
      ->orderBy('lc.createdatetime DESC')
      ->execute();
    }
    public function getLogClaimById($claimid)
    {
      return Doctrine_Core::getTable('log_claim')
      ->createQuery('lc')
      ->leftJoin('lc.Users u')
      ->where('lc.claim_id = '.$claimid)
      ->addWhere('lc.log_claim_type NOT LIKE \''.sfConfig::get('logcliam_finance').'%\'') 
      ->orderBy('lc.createdatetime DESC')
      ->execute();
    }
    
    public function getLogClaimByIdFinance($claimid)
    {
      return Doctrine_Core::getTable('log_claim')
      ->createQuery('lc')
      ->leftJoin('lc.Users u')
      ->where('lc.claim_id = '.$claimid)
      ->addWhere('lc.log_claim_type LIKE \''.sfConfig::get('logcliam_finance').'%\'')
      ->orderBy('lc.createdatetime DESC')
      ->execute();
    }
    
    public function getLogClaimByIdFinanceWork($claimid, $finance_claim_id)
    {
      return Doctrine_Core::getTable('log_claim')
      ->createQuery('lc')
      ->leftJoin('lc.Users u')
      ->where('lc.claim_id = '.$claimid)
      ->addWhere('lc.finance_claim_id = '.$finance_claim_id)
      ->addWhere('lc.log_claim_type LIKE \''.sfConfig::get('logcliam_finance').'%\'')
      ->orderBy('lc.createdatetime DESC')
      ->execute();
    }
    
    
}