<?php

/**
 * lookup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class lookup extends Pluginlookup
{
  static public $instance;

  const EMPLOYMENT_TYPE_A = 'employment_type_a';
  const EMPLOYMENT_TYPE_B = 'employment_type_b';
  const EMPLOYMENT_TYPE_C = 'employment_type_c';
  const EMPLOYMENT_TYPE_D = 'employment_type_d';
  const EMPLOYMENT_TYPE_E = 'employment_type_e';

  const EMPLOYMENT_TYPE_CHAR_A = 'A';
  const EMPLOYMENT_TYPE_CHAR_B = 'B';
  const EMPLOYMENT_TYPE_CHAR_C = 'C';
  const EMPLOYMENT_TYPE_CHAR_D = 'D';
  const EMPLOYMENT_TYPE_CHAR_E = 'E';

  const DEPARTMENT_PEOPLE_TYPE = 'department_people_type';
  const DEPARTMENT_PEOPLE_TYPE_PERMANENT = 'department_people_type_permanent';
  const DEPARTMENT_PEOPLE_TYPE_REPLACEMENT = 'department_people_type';

  const ORGANIZATION_SIGN_OWN = 'organization_sign_own';

  static public function getInstance()
  {
    return Doctrine::getTable('lookup')
      ->createQuery('l')
      ->execute();
  }

  static public function getDataName()
  {
    if (!self::$instance)
    {
      self::$instance = self::getInstance();
    }

    return self::$instance->toKeyValueArray('id', 'name');
  }

  static public function getDataLukey()
  {
    if (!self::$instance)
    {
      self::$instance = self::getInstance();
    }

    return self::$instance->toKeyValueArray('id', 'lukey');
  }

  static public function getIdByLukey($lukey)
  {
    $q = Doctrine::getTable('lookup')
      ->createQuery('l')
      ->where('l.lukey = ?', $lukey)
      ->fetchOne();

    return $q ? $q->getId() : null;
  }
}