<?php

/**
 * lookupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class lookupTable extends PluginlookupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object lookupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('lookup');
    }
    
    public function getUserStuffLookup()
    {
      $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey = \'pos\'')
        ->execute();
        return $q;  
    }
    
    public function getLookupStatus()
    {
      $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey LIKE \''.sfConfig::get('status_lookup_key').'%\'')
        ->execute();
        return $q;  
    }
    public function getOnlySex()
    {
      $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey = \''.sfConfig::get('lookup_sex').'\'')
        ->execute();
        return $q;  
    }
    
    public function getDepartmentPeople()
    {
      $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey LIKE ?', 'department_people_type%')
        ->orderBy('id ASC')
        ->execute();
        return $q;
    }

    
    public function getNds()
    {
        $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey = \''.sfConfig::get('nds').'\'')
        ->execute()->getFirst();
        if ($q) return $q->getName(); else return null;

    }
    public function getObnal()
    {
        $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey = \''.sfConfig::get('obnal').'\'')
        ->execute()->getFirst();
        if ($q) return $q->getName(); else return null;
    }
    
    /*public function getLookupStatusOpen()
    {
       $q = Doctrine_Core::getTable('lookup')
       ->createQuery('l')
        ->where('l.lukey = \''.sfConfig::get('status_lookup_key_open').'\'')
        ->fetchOne();
        return $q;  
    }*/
    
    public function getOnlyDogovor()
    {
      $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey = ?', 'dogovor')
        ->execute();
        return $q;  
    }
    
    public function getOnlyCompanyRole()
    {
      $q = Doctrine_Core::getTable('lookup')
        ->createQuery('l')
        ->where('l.lukey = ?', 'company_role')
        ->execute();
        return $q;  
    }

  public function getOnlyScope()
  {
    $q = Doctrine_Core::getTable('lookup')
      ->createQuery('l')
      ->where('l.lukey = ?', 'scope')
      ->execute();
    return $q;
  }

  public function getOnlyClientType()
  {
    $q = Doctrine_Core::getTable('lookup')
      ->createQuery('l')
      ->where('l.lukey = ?', 'client_type')
      ->execute();
    return $q;
  }

  public function getOnlyEmploymentType()
  {
    $q = Doctrine_Core::getTable('lookup')
      ->createQuery('l')
      ->where('l.lukey LIKE ?', 'employment_type%')
      ->orderBy('l.name ASC')
      ->execute();
    return $q;
  }

  public function getOnlySalaryType()
  {
    $q = Doctrine_Core::getTable('lookup')
      ->createQuery('l')
      ->where('l.lukey = ?', 'salary_type')
      ->execute();
    return $q;
  }
}