<?php

/**
 * MpkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mpk');
    }
}