<?php

/**
 * MpkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mpk');
    }

  public static function getSearchResultsAutocomplite($s)
  {
    $pattern = $s;

    $q = Doctrine::getTable('Mpk')
      ->createQuery('m')
      ->where('LOWER(m.name) LIKE ?', '%'.strtolower($pattern)."%");

    $q = $q->fetchArray();

    $result = array();
    foreach ($q as $object)
    {
      $result[$object['id']] = $object['name'];
    }

    return $result;
  }
}