<?php

/**
 * OrganizationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OrganizationType extends BaseOrganizationType
{
  const TYPE__NETWORK_ID = 1;
  const TYPE__LOCAL_ID = 2;
  const TYPE__ONCE_ID = 3;
  
  const TYPE__NETWORK = 'network';
  const TYPE__LOCAL = 'local';
  const TYPE__ONCE = 'once';
  
  static public function getIdFromType($type = self::TYPE__NETWORK)
  {
    $id = OrganizationTypeTable::getInstance()
      ->createQuery('ot')
      ->select('id')
      ->where('ot.type = ?', $type)
      ->fetchOne();
    
    return $id ? $id->getId() : null;
  }

}