<?php

/**
 * organizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class organizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object organizationTable
     */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('organization');
  }
  
  public function KuratorOrganizations()
  {
    $user_id = GlobalFunctions::getUserId();
    $q = Doctrine::getTable('organization')
      ->createQuery('o')
      ->select('o.*')
      //->leftJoin('o.contract con')
      ->leftJoin('o.Departments d')
      ->leftJoin('d.stuff_departments sd')
      ->leftJoin('sd.Stuff s')
      ->where('s.user_id = ?', $user_id)
      ->andWhere('sd.userkey = ?', sfConfig::get('claimuserkey_kurator'))
      ->orderBy('o.id')
      ->execute();
      
    return $q;
  }
 
  public static function getSearchResultsAutocomplite($s, $type = null)
  {
    $pattern = $s;
    
    $organization_type_id = OrganizationType::getIdFromType($type);
    
    if (!$organization_type_id && $type)
    {
      return array();
    }
    
    $q = Doctrine::getTable('organization')
      ->createQuery('o')
      ->where('LOWER(o.name) LIKE ?', '%'.strtolower($pattern)."%");
      
    if ($type)
    {
      $q->addWhere('organization_type_id = ?', $organization_type_id);
    }
      
    $q = $q->fetchArray();
      
    $result = array();
    foreach ($q as $organization)
    {
      $result[$organization['id']] = $organization['name'];
    }
    
    return $result;
  }

  /**
   * get organization form crm
   */
  static public function getMyOrganizationQuery()
  {
    $organization_query = self::getInstance()
      ->createQuery('o')
      ->leftJoin('o.City city')
      ->leftJoin('city.Region region')
      ->leftJoin('o.Scope scope')
      ->leftJoin('o.OrganizationUser ou')
      ->leftJoin('ou.User manager');

    $user = sfContext::getInstance()->getUser();

    if (!$user->hasCredential('crmadmin'))
    {
      $userId = $user->getId();

      $organization_query
        ->addWhere('ou.user_id = ?', $userId);
    }

    $organization_query
      ->orderBy('o.id DESC');

    return $organization_query;
  }

  /**
   * get organization for oper excel report
   */
  static public function getMyOrganizationExcelQuery()
  {
    $organization_query = self::getInstance()
      ->createQuery('o')
      ->select('o.*')
      ->leftJoin('o.City city')
      ->leftJoin('city.Region region')
      ->leftJoin('o.Dogovor dogovor')
      //->leftJoin('o.ModelContact model_contact')
      ->where('o.id = ?', 855);
      //->addWhere('model_contact.model_name = ?', ModelContact::MODEL_ORGANIZATION);

    $user = sfContext::getInstance()->getUser();

    $organization_query
      ->limit(100);

    $organization_query
      ->orderBy('o.id DESC');

    return $organization_query;
  }

  static public function getOrganizationLikeName($name)
  {
    if (!$name)
    {
      return array();
    }

    $query = Doctrine::getTable('organization')
      ->createQuery('o')
      ->where('LOWER(o.name) LIKE ?', "%".$name."%")
      ->leftJoin('o.OrganizationUser ou')
      ->leftJoin('ou.User user')
      ->leftJoin('user.Stuff stuff')
      ->execute();

    return $query;
  }
}