<?php

/**
 * OrganizationUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganizationUser');
    }
}