<?php

/**
 * organization_importanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class organization_importanceTable extends Doctrine_Table
{
  /**
     * Returns an instance of this class.
     *
     * @return object organization_importanceTable
     */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('organization_importance');
  }
  
  public function getImportanceByOrganization($org_id)
  {
      /*$contract_ids = Doctrine::getTable('Organization')
      ->createQuery('c')
      ->where('c.organization_id = '.$org_id)
      ->execute()->getPrimaryKeys()*/;
     
      return Doctrine::getTable('organization_importance')
      ->createQuery('o')
      ->leftJoin('o.Importance')
      ->where('o.organization_id = ? ', intval($org_id))
      ->execute();    
  }
  
  public function getImportanceForThisContract()
  {
    $user_id = GlobalFunctions::getUserId();
    
    $client = Doctrine::getTable('client')
      ->createQuery('c')
      ->where('user_id = ? ', $user_id)
      ->fetchOne();
      
    $org_id = $client->getOrganizationId();
       
    return Doctrine::getTable('organization_importance')
      ->createQuery('o')
      ->leftJoin('o.Importance')
      ->where('o.organization_id = ? ', intval($org_id))
      ->execute();    
  }
  
  public function getImportanceForDispatcher($claim)
  {
                                         
    $org_id = $claim->getOrganizationId();
   
    return Doctrine::getTable('organization_importance')
    ->createQuery('c')
    ->where('organization_id = ? ', $org_id)
    ->execute();    
  }

  public function noInfo()
  {
    return array();
  }
}