<?php

/**
 * SalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Salary');
    }
}