<?php

/**
 * sfuff_cityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfuff_cityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfuff_cityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfuff_city');
    }
}