<?php

/**
 * stuff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class stuff extends Basestuff
{
   public function __toString()
   {
       $user = Doctrine::getTable('sfGuardUser')->find($this->user_id);
       if ($user<>null) return $user->getLastName().' '.$user->getFirstName(); else return '';
   }
   
   
   public function getExistKurator($department_id, $claimtype_id)
   {
       $user = Doctrine::getTable('stuff')
       ->createQuery('s')
       ->select('s.user_id')
       ->leftJoin('s.StuffDepartments sd')
       ->where('sd.departments_id = '.$department_id)
       ->addWhere('claimtype_id = '.$claimtype_id)
       ->addWhere('userkey = \''.sfConfig::get('claimuserkey_kurator').'\'')
       ->execute();
       if ($user) return $user;  else return null;
       //return null;
   }
   public function getExistStuff($department_id, $claimtype_id)
   {
       $user = Doctrine::getTable('stuff')
       ->createQuery('s')
       ->select('s.user_id')
       ->leftJoin('s.StuffDepartments sd')
       ->where('sd.departments_id = '.$department_id)
       ->addWhere('claimtype_id = '.$claimtype_id)
       ->addWhere('userkey = \''.sfConfig::get('claimuserkey_stuff').'\'')
        ->execute();
       if (count($user)) return $user;  else return null;
       //return null;
   }
   
   
}
