<?php

/**
 * stuffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class stuffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object stuffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('stuff');
    }
    
    public function getAllKurators($departments_id)
    {
        //die($departments_id);
        //$this->getObject->
        $q = Doctrine::getTable('Stuff')
        ->createQuery('s')
        //->leftJoin('s. cu')
        ->leftJoin('s.Companystructure gs')
        ->leftJoin('gs.CompanystructureRegion gsr')
        ->leftJoin('gsr.Region r')
        ->leftJoin('r.City c')
        ->leftJoin('c.Departments d')
        ->leftJoin('d.Claim cl')
        //->leftJoin('d.Departments d')
        ->where('s.companystructure_id = gs.id')
        ->addWhere('gs.id = gsr.companystructure_id')
        ->addWhere('gsr.region_id = r.id')
        ->addWhere('r.id = c.region_id')
        ->addWhere('c.id = d.city_id')
        ->addWhere('d.id = '.$departments_id)
        //->addWhere('c.departments_id = '.$departments_id)
        ->execute();
        return $q;
    }
    
    public function getAllStuff($departments_id)
    {
        //die($departments_id);
        //$this->getObject->
        $q = Doctrine::getTable('Stuff')
        ->createQuery('s')
        //->leftJoin('s. cu')
        ->leftJoin('s.Companystructure gs')
        ->leftJoin('s.Users usr')
        ->leftJoin('gs.CompanystructureRegion gsr')
        ->leftJoin('gsr.Region r')
        ->leftJoin('r.City c')
        ->leftJoin('c.Departments d')
        ->leftJoin('d.Claim cl')
        //->leftJoin('d.Departments d')
        ->where('s.companystructure_id = gs.id')
        ->addWhere('gs.id = gsr.companystructure_id')
        ->addWhere('gsr.region_id = r.id')
        ->addWhere('r.id = c.region_id')
        ->addWhere('c.id = d.city_id')
        ->addWhere('d.id = '.$departments_id)
        ->orderBy('usr.last_name')
        //->addWhere('c.departments_id = '.$departments_id)
        ->execute();
        return $q;
    }
    
    public function getAllPersons()
    {
        $q = Doctrine::getTable('Stuff')
        ->createQuery('s')
        ->leftJoin('s.Users usr')
        ->orderBy('usr.last_name')
        ->execute();
        return $q;
    }
    
    public function getStuffDepartmentsList($stuff_id)
    {
        $stuff = Doctrine::getTable('stuff')
        ->createQuery('s')
        ->where('user_id = '.$stuff_id)
        ->execute()->getFirst();
        $stuff_departments_list = Doctrine::getTable('stuff_departments')
        ->createQuery('sd')
        ->select('sd.stuff_id, sd.userkey, ct.name, d.address, contr.id, o.name')
        ->leftJoin('sd.Claimtype ct')
        ->leftJoin('sd.Departments d')
        ->leftJoin('d.contract contr')
        ->leftJoin('contr.organization o')
        ->where('sd.stuff_id = '.$stuff->getId())
        ->execute();
        return $stuff_departments_list;
    }
    
    

}