<?php

/**
 * stuff_departmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class stuff_departmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object stuff_departmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('stuff_departments');
    }
    
    public function Delete($departmentsstuff_id)
    {
        Doctrine::getTable('stuff_departments')
        ->createQuery('sd')
        ->where('sd.id = '.$departmentsstuff_id)
        ->delete()
        ->execute(); 
    }
}