<?php

/**
 * worksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class worksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object worksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('works');
    }
}