<?php

/**
 * PluginTechnicalParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTechnicalParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTechnicalParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTechnicalParam');
    }
}