ajax_departments_by_organization:
  url:   /ajax_departments_by_organization
  param: { module: ajaxdata, action: departmentsByOrganization }

idea_goal:
  class: sfDoctrineRouteCollection
  options:
    model:                IdeaGoal
    module:               idea_goal
    prefix_path:          /idea_goal
    column:               id
    with_wildcard_routes: true

handling_more_info_type:
  class: sfDoctrineRouteCollection
  options:
    model:                HandlingMoreInfoType
    module:               handling_more_info_type
    prefix_path:          /handling_more_info_type
    column:               id
    with_wildcard_routes: true

department_people_position:
  class: sfDoctrineRouteCollection
  options:
    model:                DepartmentPeoplePosition
    module:               department_people_position
    prefix_path:          /department_people_position
    column:               id
    with_wildcard_routes: true

handling_result:
  class: sfDoctrineRouteCollection
  options:
    model:                HandlingResult
    module:               handling_result
    prefix_path:          /handling_result
    column:               id
    with_wildcard_routes: true

salary:
  class: sfDoctrineRouteCollection
  options:
    model:                Salary
    module:               salary
    prefix_path:          /salary
    column:               id
    with_wildcard_routes: true

handling_type:
  class: sfDoctrineRouteCollection
  options:
    model:                HandlingType
    module:               handling_type
    prefix_path:          /handling_type
    column:               id
    with_wildcard_routes: true

handling_status:
  class: sfDoctrineRouteCollection
  options:
    model:                HandlingStatus
    module:               handling_status
    prefix_path:          /handling_status
    column:               id
    with_wildcard_routes: true

handling_message_type:
  class: sfDoctrineRouteCollection
  options:
    model:                HandlingMessageType
    module:               handling_message_type
    prefix_path:          /handling_message_type
    column:               id
    with_wildcard_routes: true

organization_importance:
  class: sfDoctrineRouteCollection
  options:
    model:                organization_importance
    module:               organization_importance
    prefix_path:          /organization_importance
    column:               id
    with_wildcard_routes: true

technical_param_type:
  class: sfDoctrineRouteCollection
  options:
    model:                TechnicalParamType
    module:               technical_param_type
    prefix_path:          /technical_param_type
    column:               id
    with_wildcard_routes: true

technical_param:
  class: sfDoctrineRouteCollection
  options:
    model:                TechnicalParam
    module:               technical_param
    prefix_path:          /technical_param
    column:               id
    with_wildcard_routes: true

departments_status:
  class: sfDoctrineRouteCollection
  options:
    model:                DepartmentsStatus
    module:               departments_status
    prefix_path:          /departments_status
    column:               id
    with_wildcard_routes: true

departments_type:
  class: sfDoctrineRouteCollection
  options:
    model:                DepartmentsType
    module:               departments_type
    prefix_path:          /departments_type
    column:               id
    with_wildcard_routes: true

widget_list:
  class: sfDoctrineRouteCollection
  options:
    model:                WidgetList
    module:               widget_list
    prefix_path:          /widget_list
    column:               id
    with_wildcard_routes: true

organization_type:
  class: sfDoctrineRouteCollection
  options:
    model:                OrganizationType
    module:               organization_type
    prefix_path:          /organization_type
    column:               id
    with_wildcard_routes: true

departments:
  class: sfDoctrineRouteCollection
  options:
    model:                departments
    module:               departmentsorganization
    prefix_path:          /departmentsorganization
    column:               id
    with_wildcard_routes: true

dop_dogovor:
  class: sfDoctrineRouteCollection
  options:
    model:                DopDogovor
    module:               dopdogovor
    prefix_path:          /dopdogovor
    column:               id
    with_wildcard_routes: true

dogovor:
  class: sfDoctrineRouteCollection
  options:
    model:                Dogovor
    module:               dogovor
    prefix_path:          /dogovor
    column:               id
    with_wildcard_routes: true

stuffdepartmentslist:
  url:   /stuffdepartmentslist
  param: { module: stuff, action: show_departmentslist }

fc_costsn_types:
  class: sfDoctrineRouteCollection
  options:
    model:                FcCostsnTypes
    module:               FcCostsnTypes
    prefix_path:          /FcCostsnTypes
    column:               id
    with_wildcard_routes: true

fc_costsn:
  class: sfDoctrineRouteCollection
  options:
    model:                FcCostsn
    module:               FcCostsn
    prefix_path:          /FcCostsn
    column:               id
    with_wildcard_routes: true

departmentsstuff:
  class: sfDoctrineRouteCollection
  options:
    model:                departments
    module:               departmentsstuff
    prefix_path:          /departmentsstuff
    column:               id
    with_wildcard_routes: true

district:
  class: sfDoctrineRouteCollection
  options:
    model:                District
    module:               district
    prefix_path:          /district
    column:               id
    with_wildcard_routes: true

contract_importance:
  class: sfDoctrineRouteCollection
  options:
    model:                contract_importance
    module:               contract_importance
    prefix_path:          /contract_importance
    column:               id
    with_wildcard_routes: true

status:
  class: sfDoctrineRouteCollection
  options:
    model:                status
    module:               status
    prefix_path:          /status
    column:               id
    with_wildcard_routes: true


  
stuff_departments:
  class: sfDoctrineRouteCollection
  options:
    model:                stuff_departments
    module:               stuff_departments
    prefix_path:          /stuff_departments
    column:               id
    with_wildcard_routes: true

region:
  class: sfDoctrineRouteCollection
  options:
    model:                region
    module:               region
    prefix_path:          /region
    column:               id
    with_wildcard_routes: true

contract:
  class: sfDoctrineRouteCollection
  options:
    model:                contract
    module:               contract
    prefix_path:          /contract
    column:               id
    with_wildcard_routes: true

organization:
  class: sfDoctrineRouteCollection
  options:
    model:                organization
    module:               organization
    prefix_path:          /organization
    column:               id
    with_wildcard_routes: true

city:
  class: sfDoctrineRouteCollection
  options:
    model:                city
    module:               city
    prefix_path:          /city
    column:               id
    with_wildcard_routes: true

userstuff:
  class: sfDoctrineRouteCollection
  options:
    model:                userstuff
    module:               stuff
    prefix_path:          /stuff
    column:               id
    with_wildcard_routes: true

userclient:
  class: sfDoctrineRouteCollection
  options:
    model:                userclient
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true

clientinfo:
  class: sfDoctrineRouteCollection
  options:
    model:                client
    module:               clientinfo
    prefix_path:          /clientinfo
    column:               id
    with_wildcard_routes: true

     
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout } 
  

  
cinfo:
  url:   /cinfo
  param: { module: cinfo, action: index }  
  
sinfo:
  url:   /sinfo
  param: { module: sinfo, action: index } 

homepage:
  url:   /
  param: { module: client, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

