<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
/*    public function getAllStuff()
    {
        $q = Doctrine_Core::getTable('sfGuardUser')
        ->createQuery('c')
        ->where('c.id = 1')
        ->execute();
        return 0;
    }      */
    
    public function getAllStuff()
    {
       return Doctrine::getTable('sfGuardUser')
       ->createQuery('sf')
       ->innerJoin('sf.Stuff s') 
       ->where('sf.id = s.user_id')
       ->addWhere('sf.is_fired =? ',false)
       ->orderBy('sf.last_name') 
       ->execute();

    }
    
    public function getFreeUsers()
    {
      $q = Doctrine_Core::getTable('sfGuardUser')
        ->createQuery('r')
        ->from('sfGuardUser r, stuff s, client c')
        //->leftJoin('stuff s, client c')
        //->leftJoin('client c')
        ->where('r.id <> s.user_id')
        ->addWhere('r.id <> c.user_id')
        ->execute();
        return $q;  
    }
    
    public function getAllStuffFor()
    {
      $stuff = Doctrine_Query::create() 
       ->from('sfGuardUser r') 
       ->innerJoin('r.Stuff s') 
       ->where('r.id = s.user_id') 
       ->addWhere('s.stuffclass = \''.sfConfig::get('claimuserkey_kurator').'\'') 
       ->execute();
       if ($stuff<>null) return $stuff;
       else return null;
    }
    
    public function getAllClientFor()
    {
      $client = Doctrine_Query::create() 
       ->from('sfGuardUser r') 
       ->innerJoin('r.Stuff c') 
       ->where('r.id = c.user_id') 
       ->execute();
       if ($client<>null) return $client;
       else return null;
    }
    

}