<?php

/**
 * UserContactinfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserContactinfoTable extends PluginUserContactinfoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserContactinfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserContactinfo');
    }
}