<?php

/**
 * PluginContactinfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactinfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactinfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactinfo');
    }
}