<?php

/**
 * PluginlookupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginlookupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginlookupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pluginlookup');
    }
}