<?php

/**
 * BaseGlobalMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $description
 * @property timestamp $createdatetime
 * @property sfGuardUser $User
 * 
 * @method integer       getId()             Returns the current record's "id" value
 * @method integer       getUserId()         Returns the current record's "user_id" value
 * @method string        getTitle()          Returns the current record's "title" value
 * @method string        getDescription()    Returns the current record's "description" value
 * @method timestamp     getCreatedatetime() Returns the current record's "createdatetime" value
 * @method sfGuardUser   getUser()           Returns the current record's "User" value
 * @method GlobalMessage setId()             Sets the current record's "id" value
 * @method GlobalMessage setUserId()         Sets the current record's "user_id" value
 * @method GlobalMessage setTitle()          Sets the current record's "title" value
 * @method GlobalMessage setDescription()    Sets the current record's "description" value
 * @method GlobalMessage setCreatedatetime() Sets the current record's "createdatetime" value
 * @method GlobalMessage setUser()           Sets the current record's "User" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGlobalMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('global_message');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('createdatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}