generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Dogovor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dogovor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, organization, name, startdatetime, stopdatetime, city, subject, is_active, dogovor_type, mashtab]
        
      filter:  
        class: false 
      form:    ~
      edit:    ~
      new:     ~
