<?php

/**
 * BaseHandlingUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $handling_id
 * @property integer $user_id
 * @property integer $part
 * @property Handling $Handling
 * @property sfGuardUser $User
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getHandlingId()  Returns the current record's "handling_id" value
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method integer      getPart()        Returns the current record's "part" value
 * @method Handling     getHandling()    Returns the current record's "Handling" value
 * @method sfGuardUser  getUser()        Returns the current record's "User" value
 * @method HandlingUser setId()          Sets the current record's "id" value
 * @method HandlingUser setHandlingId()  Sets the current record's "handling_id" value
 * @method HandlingUser setUserId()      Sets the current record's "user_id" value
 * @method HandlingUser setPart()        Sets the current record's "part" value
 * @method HandlingUser setHandling()    Sets the current record's "Handling" value
 * @method HandlingUser setUser()        Sets the current record's "User" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHandlingUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('handling_user');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('handling_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('part', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Handling', array(
             'local' => 'handling_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}