<?php

/**
 * BaseHandlingMoreInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $handling_id
 * @property integer $handling_more_info_type_id
 * @property string $value
 * @property Handling $Handling
 * @property HandlingMoreInfoType $HandlingMoreInfoType
 * 
 * @method integer              getId()                         Returns the current record's "id" value
 * @method integer              getHandlingId()                 Returns the current record's "handling_id" value
 * @method integer              getHandlingMoreInfoTypeId()     Returns the current record's "handling_more_info_type_id" value
 * @method string               getValue()                      Returns the current record's "value" value
 * @method Handling             getHandling()                   Returns the current record's "Handling" value
 * @method HandlingMoreInfoType getHandlingMoreInfoType()       Returns the current record's "HandlingMoreInfoType" value
 * @method HandlingMoreInfo     setId()                         Sets the current record's "id" value
 * @method HandlingMoreInfo     setHandlingId()                 Sets the current record's "handling_id" value
 * @method HandlingMoreInfo     setHandlingMoreInfoTypeId()     Sets the current record's "handling_more_info_type_id" value
 * @method HandlingMoreInfo     setValue()                      Sets the current record's "value" value
 * @method HandlingMoreInfo     setHandling()                   Sets the current record's "Handling" value
 * @method HandlingMoreInfo     setHandlingMoreInfoType()       Sets the current record's "HandlingMoreInfoType" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHandlingMoreInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('handling_more_info');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('handling_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('handling_more_info_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Handling', array(
             'local' => 'handling_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('HandlingMoreInfoType', array(
             'local' => 'handling_more_info_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}