<?php

/**
 * BaseHandlingMessageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property Doctrine_Collection $HandlingMessage
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getSlug()            Returns the current record's "slug" value
 * @method Doctrine_Collection getHandlingMessage() Returns the current record's "HandlingMessage" collection
 * @method HandlingMessageType setId()              Sets the current record's "id" value
 * @method HandlingMessageType setName()            Sets the current record's "name" value
 * @method HandlingMessageType setSlug()            Sets the current record's "slug" value
 * @method HandlingMessageType setHandlingMessage() Sets the current record's "HandlingMessage" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHandlingMessageType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('handling_message_type');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('slug', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HandlingMessage', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}