generator:
  class: sfDoctrineGenerator
  param:
    model_class:           organization_importance
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organization_importance
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, organization, importance]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
