<?php

/**
 * TenderkeywordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TenderkeywordsTable extends PluginTenderkeywordsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TenderkeywordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tenderkeywords');
    }
}