generator:
  class: sfDoctrineGenerator
  param:
    model_class:           userstuff
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          userstuff
    with_doctrine_route:   true

    config:
      fields:
        password_again: { label: "Password (again)" }

      list:
        title:   User list
        display:  [=username, first_name, last_name, departments]
      
      form:
        class: userstuffForm

      
      filter:
        display: [username, first_name, last_name]
        
      