<?php

/**
 * PluginHandlingStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHandlingStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHandlingStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHandlingStatus');
    }
}