<?php

/**
 * Baseclient_departments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property integer $departments_id
 * @property departments $Departments
 * @property client $Client
 * 
 * @method integer            getClientId()       Returns the current record's "client_id" value
 * @method integer            getDepartmentsId()  Returns the current record's "departments_id" value
 * @method departments        getDepartments()    Returns the current record's "Departments" value
 * @method client             getClient()         Returns the current record's "Client" value
 * @method client_departments setClientId()       Sets the current record's "client_id" value
 * @method client_departments setDepartmentsId()  Sets the current record's "departments_id" value
 * @method client_departments setDepartments()    Sets the current record's "Departments" value
 * @method client_departments setClient()         Sets the current record's "Client" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseclient_departments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_departments');
        $this->hasColumn('client_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('departments_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('departments as Departments', array(
             'local' => 'departments_id',
             'foreign' => 'id'));

        $this->hasOne('client as Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));
    }
}