<?php

/**
 * Baseclaimtype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Stuff
 * @property Doctrine_Collection $Groupclaim
 * @property Doctrine_Collection $Claim
 * @property Doctrine_Collection $StuffDepartmnets
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method Doctrine_Collection getStuff()            Returns the current record's "Stuff" collection
 * @method Doctrine_Collection getGroupclaim()       Returns the current record's "Groupclaim" collection
 * @method Doctrine_Collection getClaim()            Returns the current record's "Claim" collection
 * @method Doctrine_Collection getStuffDepartmnets() Returns the current record's "StuffDepartmnets" collection
 * @method claimtype           setId()               Sets the current record's "id" value
 * @method claimtype           setName()             Sets the current record's "name" value
 * @method claimtype           setDescription()      Sets the current record's "description" value
 * @method claimtype           setStuff()            Sets the current record's "Stuff" collection
 * @method claimtype           setGroupclaim()       Sets the current record's "Groupclaim" collection
 * @method claimtype           setClaim()            Sets the current record's "Claim" collection
 * @method claimtype           setStuffDepartmnets() Sets the current record's "StuffDepartmnets" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseclaimtype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimtype');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('stuff as Stuff', array(
             'refClass' => 'stuff_departments',
             'local' => 'claimtype_id',
             'foreign' => 'stuff_id'));

        $this->hasMany('Groupclaim', array(
             'local' => 'id',
             'foreign' => 'claimtype_id'));

        $this->hasMany('claim as Claim', array(
             'local' => 'id',
             'foreign' => 'claimtype_id'));

        $this->hasMany('stuff_departments as StuffDepartmnets', array(
             'local' => 'id',
             'foreign' => 'claimtype_id'));
    }
}