<?php

/**
 * BaseHelpdeskGuid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $helpdesk_name
 * @property integer $helpdesk_id
 * @property string $guid
 * 
 * @method string       getHelpdeskName()  Returns the current record's "helpdesk_name" value
 * @method integer      getHelpdeskId()    Returns the current record's "helpdesk_id" value
 * @method string       getGuid()          Returns the current record's "guid" value
 * @method HelpdeskGuid setHelpdeskName()  Sets the current record's "helpdesk_name" value
 * @method HelpdeskGuid setHelpdeskId()    Sets the current record's "helpdesk_id" value
 * @method HelpdeskGuid setGuid()          Sets the current record's "guid" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHelpdeskGuid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('helpdesk_guid');
        $this->hasColumn('helpdesk_name', 'string', 50, array(
             'primary' => true,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('helpdesk_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('guid', 'string', 32, array(
             'primary' => true,
             'type' => 'string',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}