<?php

/**
 * BaseHelpdeskProtocol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $model_name
 * @property integer $model_id
 * @property string $field_name
 * @property string $value_before
 * @property string $value_after
 * @property timestamp $created_at
 * @property string $action
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method string           getModelName()    Returns the current record's "model_name" value
 * @method integer          getModelId()      Returns the current record's "model_id" value
 * @method string           getFieldName()    Returns the current record's "field_name" value
 * @method string           getValueBefore()  Returns the current record's "value_before" value
 * @method string           getValueAfter()   Returns the current record's "value_after" value
 * @method timestamp        getCreatedAt()    Returns the current record's "created_at" value
 * @method string           getAction()       Returns the current record's "action" value
 * @method HelpdeskProtocol setId()           Sets the current record's "id" value
 * @method HelpdeskProtocol setModelName()    Sets the current record's "model_name" value
 * @method HelpdeskProtocol setModelId()      Sets the current record's "model_id" value
 * @method HelpdeskProtocol setFieldName()    Sets the current record's "field_name" value
 * @method HelpdeskProtocol setValueBefore()  Sets the current record's "value_before" value
 * @method HelpdeskProtocol setValueAfter()   Sets the current record's "value_after" value
 * @method HelpdeskProtocol setCreatedAt()    Sets the current record's "created_at" value
 * @method HelpdeskProtocol setAction()       Sets the current record's "action" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHelpdeskProtocol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('helpdesk_protocol');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('model_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('model_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('field_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('value_before', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('value_after', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('action', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}