<?php

/**
 * Baseclaim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mpk
 * @property integer $claimtype_id
 * @property integer $departments_id
 * @property timestamp $createdatetime
 * @property boolean $isclosedclient
 * @property integer $status_id
 * @property integer $smeta_status_id
 * @property timestamp $closedatetime
 * @property integer $contract_importance_id
 * @property integer $organization_importance_id
 * @property string $description
 * @property string $stuffdescription
 * @property string $ourcosts
 * @property boolean $isclosedstuff
 * @property string $bill_number
 * @property string $bill_description
 * @property timestamp $bill_date
 * @property timestamp $akt_date
 * @property string $smeta_costs
 * @property string $smeta_number
 * @property integer $organization_type_id
 * @property departments $Departments
 * @property contract_importance $ContractImportance
 * @property organization_importance $OrganizationImportance
 * @property claimtype $Claimtype
 * @property status $Status
 * @property status $SmetaStatus
 * @property Doctrine_Collection $Documents
 * @property Doctrine_Collection $FinanceClaim
 * @property OrganizationType $OrganizationType
 * @property Doctrine_Collection $GroupclaimClaim
 * @property Doctrine_Collection $works
 * @property Doctrine_Collection $DocumentsClaim
 * @property Doctrine_Collection $log_claim
 * @property Doctrine_Collection $Comment
 * @property Doctrine_Collection $claim_works
 * @property Doctrine_Collection $ClaimUsers
 * 
 * @method integer                 getId()                         Returns the current record's "id" value
 * @method string                  getMpk()                        Returns the current record's "mpk" value
 * @method integer                 getClaimtypeId()                Returns the current record's "claimtype_id" value
 * @method integer                 getDepartmentsId()              Returns the current record's "departments_id" value
 * @method timestamp               getCreatedatetime()             Returns the current record's "createdatetime" value
 * @method boolean                 getIsclosedclient()             Returns the current record's "isclosedclient" value
 * @method integer                 getStatusId()                   Returns the current record's "status_id" value
 * @method integer                 getSmetaStatusId()              Returns the current record's "smeta_status_id" value
 * @method timestamp               getClosedatetime()              Returns the current record's "closedatetime" value
 * @method integer                 getContractImportanceId()       Returns the current record's "contract_importance_id" value
 * @method integer                 getOrganizationImportanceId()   Returns the current record's "organization_importance_id" value
 * @method string                  getDescription()                Returns the current record's "description" value
 * @method string                  getStuffdescription()           Returns the current record's "stuffdescription" value
 * @method string                  getOurcosts()                   Returns the current record's "ourcosts" value
 * @method boolean                 getIsclosedstuff()              Returns the current record's "isclosedstuff" value
 * @method string                  getBillNumber()                 Returns the current record's "bill_number" value
 * @method string                  getBillDescription()            Returns the current record's "bill_description" value
 * @method timestamp               getBillDate()                   Returns the current record's "bill_date" value
 * @method timestamp               getAktDate()                    Returns the current record's "akt_date" value
 * @method string                  getSmetaCosts()                 Returns the current record's "smeta_costs" value
 * @method string                  getSmetaNumber()                Returns the current record's "smeta_number" value
 * @method integer                 getOrganizationTypeId()         Returns the current record's "organization_type_id" value
 * @method departments             getDepartments()                Returns the current record's "Departments" value
 * @method contract_importance     getContractImportance()         Returns the current record's "ContractImportance" value
 * @method organization_importance getOrganizationImportance()     Returns the current record's "OrganizationImportance" value
 * @method claimtype               getClaimtype()                  Returns the current record's "Claimtype" value
 * @method status                  getStatus()                     Returns the current record's "Status" value
 * @method status                  getSmetaStatus()                Returns the current record's "SmetaStatus" value
 * @method Doctrine_Collection     getDocuments()                  Returns the current record's "Documents" collection
 * @method Doctrine_Collection     getFinanceClaim()               Returns the current record's "FinanceClaim" collection
 * @method OrganizationType        getOrganizationType()           Returns the current record's "OrganizationType" value
 * @method Doctrine_Collection     getGroupclaimClaim()            Returns the current record's "GroupclaimClaim" collection
 * @method Doctrine_Collection     getWorks()                      Returns the current record's "works" collection
 * @method Doctrine_Collection     getDocumentsClaim()             Returns the current record's "DocumentsClaim" collection
 * @method Doctrine_Collection     getLogClaim()                   Returns the current record's "log_claim" collection
 * @method Doctrine_Collection     getComment()                    Returns the current record's "Comment" collection
 * @method Doctrine_Collection     getClaimWorks()                 Returns the current record's "claim_works" collection
 * @method Doctrine_Collection     getClaimUsers()                 Returns the current record's "ClaimUsers" collection
 * @method claim                   setId()                         Sets the current record's "id" value
 * @method claim                   setMpk()                        Sets the current record's "mpk" value
 * @method claim                   setClaimtypeId()                Sets the current record's "claimtype_id" value
 * @method claim                   setDepartmentsId()              Sets the current record's "departments_id" value
 * @method claim                   setCreatedatetime()             Sets the current record's "createdatetime" value
 * @method claim                   setIsclosedclient()             Sets the current record's "isclosedclient" value
 * @method claim                   setStatusId()                   Sets the current record's "status_id" value
 * @method claim                   setSmetaStatusId()              Sets the current record's "smeta_status_id" value
 * @method claim                   setClosedatetime()              Sets the current record's "closedatetime" value
 * @method claim                   setContractImportanceId()       Sets the current record's "contract_importance_id" value
 * @method claim                   setOrganizationImportanceId()   Sets the current record's "organization_importance_id" value
 * @method claim                   setDescription()                Sets the current record's "description" value
 * @method claim                   setStuffdescription()           Sets the current record's "stuffdescription" value
 * @method claim                   setOurcosts()                   Sets the current record's "ourcosts" value
 * @method claim                   setIsclosedstuff()              Sets the current record's "isclosedstuff" value
 * @method claim                   setBillNumber()                 Sets the current record's "bill_number" value
 * @method claim                   setBillDescription()            Sets the current record's "bill_description" value
 * @method claim                   setBillDate()                   Sets the current record's "bill_date" value
 * @method claim                   setAktDate()                    Sets the current record's "akt_date" value
 * @method claim                   setSmetaCosts()                 Sets the current record's "smeta_costs" value
 * @method claim                   setSmetaNumber()                Sets the current record's "smeta_number" value
 * @method claim                   setOrganizationTypeId()         Sets the current record's "organization_type_id" value
 * @method claim                   setDepartments()                Sets the current record's "Departments" value
 * @method claim                   setContractImportance()         Sets the current record's "ContractImportance" value
 * @method claim                   setOrganizationImportance()     Sets the current record's "OrganizationImportance" value
 * @method claim                   setClaimtype()                  Sets the current record's "Claimtype" value
 * @method claim                   setStatus()                     Sets the current record's "Status" value
 * @method claim                   setSmetaStatus()                Sets the current record's "SmetaStatus" value
 * @method claim                   setDocuments()                  Sets the current record's "Documents" collection
 * @method claim                   setFinanceClaim()               Sets the current record's "FinanceClaim" collection
 * @method claim                   setOrganizationType()           Sets the current record's "OrganizationType" value
 * @method claim                   setGroupclaimClaim()            Sets the current record's "GroupclaimClaim" collection
 * @method claim                   setWorks()                      Sets the current record's "works" collection
 * @method claim                   setDocumentsClaim()             Sets the current record's "DocumentsClaim" collection
 * @method claim                   setLogClaim()                   Sets the current record's "log_claim" collection
 * @method claim                   setComment()                    Sets the current record's "Comment" collection
 * @method claim                   setClaimWorks()                 Sets the current record's "claim_works" collection
 * @method claim                   setClaimUsers()                 Sets the current record's "ClaimUsers" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseclaim extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claim');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('mpk', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('claimtype_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('departments_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('createdatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('isclosedclient', 'boolean', null, array(
             'default' => false,
             'type' => 'boolean',
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('smeta_status_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('closedatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('contract_importance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organization_importance_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('stuffdescription', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ourcosts', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('isclosedstuff', 'boolean', null, array(
             'default' => false,
             'type' => 'boolean',
             ));
        $this->hasColumn('bill_number', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('bill_description', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('bill_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('akt_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('smeta_costs', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('smeta_number', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('organization_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('departments as Departments', array(
             'local' => 'departments_id',
             'foreign' => 'id'));

        $this->hasOne('contract_importance as ContractImportance', array(
             'local' => 'contract_importance_id',
             'foreign' => 'id'));

        $this->hasOne('organization_importance as OrganizationImportance', array(
             'local' => 'organization_importance_id',
             'foreign' => 'id'));

        $this->hasOne('claimtype as Claimtype', array(
             'local' => 'claimtype_id',
             'foreign' => 'id'));

        $this->hasOne('status as Status', array(
             'local' => 'status_id',
             'foreign' => 'id'));

        $this->hasOne('status as SmetaStatus', array(
             'local' => 'smeta_status_id',
             'foreign' => 'id'));

        $this->hasMany('Documents', array(
             'refClass' => 'DocumentsClaim',
             'local' => 'claim_id',
             'foreign' => 'documents_id'));

        $this->hasMany('finance_claim as FinanceClaim', array(
             'local' => 'id',
             'foreign' => 'claim_id'));

        $this->hasOne('OrganizationType', array(
             'local' => 'organization_type_id',
             'foreign' => 'id'));

        $this->hasMany('GroupclaimClaim', array(
             'local' => 'id',
             'foreign' => 'claim_id'));

        $this->hasMany('works', array(
             'refClass' => 'claim_works',
             'local' => 'claim_id',
             'foreign' => 'works_id'));

        $this->hasMany('DocumentsClaim', array(
             'local' => 'id',
             'foreign' => 'claim_id'));

        $this->hasMany('log_claim', array(
             'local' => 'id',
             'foreign' => 'claim_id'));

        $this->hasMany('comments as Comment', array(
             'local' => 'id',
             'foreign' => 'claim_id'));

        $this->hasMany('claim_works', array(
             'local' => 'id',
             'foreign' => 'claim_id'));

        $this->hasMany('claimusers as ClaimUsers', array(
             'local' => 'id',
             'foreign' => 'claim_id'));
    }
}