<?php

/**
 * BasePlannedAccrual
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property date $period
 * @property string $type
 * @property string $value
 * @property integer $department_people_id
 * @property DepartmentPeople $DepartmentPeople
 * 
 * @method integer          getId()                   Returns the current record's "id" value
 * @method string           getName()                 Returns the current record's "name" value
 * @method string           getCode()                 Returns the current record's "code" value
 * @method date             getPeriod()               Returns the current record's "period" value
 * @method string           getType()                 Returns the current record's "type" value
 * @method string           getValue()                Returns the current record's "value" value
 * @method integer          getDepartmentPeopleId()   Returns the current record's "department_people_id" value
 * @method DepartmentPeople getDepartmentPeople()     Returns the current record's "DepartmentPeople" value
 * @method PlannedAccrual   setId()                   Sets the current record's "id" value
 * @method PlannedAccrual   setName()                 Sets the current record's "name" value
 * @method PlannedAccrual   setCode()                 Sets the current record's "code" value
 * @method PlannedAccrual   setPeriod()               Sets the current record's "period" value
 * @method PlannedAccrual   setType()                 Sets the current record's "type" value
 * @method PlannedAccrual   setValue()                Sets the current record's "value" value
 * @method PlannedAccrual   setDepartmentPeopleId()   Sets the current record's "department_people_id" value
 * @method PlannedAccrual   setDepartmentPeople()     Sets the current record's "DepartmentPeople" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlannedAccrual extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planned_accrual');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('period', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('value', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('department_people_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DepartmentPeople', array(
             'local' => 'department_people_id',
             'foreign' => 'id'));
    }
}