<?php

/**
 * BaseOrganizationUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $organization_id
 * @property integer $user_id
 * @property organization $Organization
 * @property sfGuardUser $User
 * 
 * @method integer          getOrganizationId()  Returns the current record's "organization_id" value
 * @method integer          getUserId()          Returns the current record's "user_id" value
 * @method organization     getOrganization()    Returns the current record's "Organization" value
 * @method sfGuardUser      getUser()            Returns the current record's "User" value
 * @method OrganizationUser setOrganizationId()  Sets the current record's "organization_id" value
 * @method OrganizationUser setUserId()          Sets the current record's "user_id" value
 * @method OrganizationUser setOrganization()    Sets the current record's "Organization" value
 * @method OrganizationUser setUser()            Sets the current record's "User" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizationUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization_user');
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'autoincrement' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('organization as Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}