<?php

/**
 * BaseDogovor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $prolongation
 * @property integer $organization_id
 * @property string $name
 * @property string $number
 * @property timestamp $startdatetime
 * @property timestamp $stopdatetime
 * @property integer $companystructure_id
 * @property integer $city_id
 * @property string $subject
 * @property string $filepath
 * @property boolean $is_active
 * @property integer $dogovor_type_id
 * @property integer $company_role_id
 * @property enum $mashtab
 * @property integer $stuff_id
 * @property integer $user_id
 * @property float $total
 * @property string $maturity
 * @property boolean $completion_notice
 * @property integer $payment_deferment
 * @property string $prolongation_term
 * @property date $launch_date
 * @property float $summ_month_vat
 * @property float $planned_pf1
 * @property float $planned_pf1_percent
 * @property city $City
 * @property organization $Organization
 * @property lookup $DogovorType
 * @property lookup $CompanyRole
 * @property companystructure $Companystructure
 * @property sfGuardUser $User
 * @property stuff $Stuff
 * @property Doctrine_Collection $DopDogovor
 * @property Doctrine_Collection $DogovorDepartment
 * @property Doctrine_Collection $DogovorHandling
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method boolean             getProlongation()        Returns the current record's "prolongation" value
 * @method integer             getOrganizationId()      Returns the current record's "organization_id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getNumber()              Returns the current record's "number" value
 * @method timestamp           getStartdatetime()       Returns the current record's "startdatetime" value
 * @method timestamp           getStopdatetime()        Returns the current record's "stopdatetime" value
 * @method integer             getCompanystructureId()  Returns the current record's "companystructure_id" value
 * @method integer             getCityId()              Returns the current record's "city_id" value
 * @method string              getSubject()             Returns the current record's "subject" value
 * @method string              getFilepath()            Returns the current record's "filepath" value
 * @method boolean             getIsActive()            Returns the current record's "is_active" value
 * @method integer             getDogovorTypeId()       Returns the current record's "dogovor_type_id" value
 * @method integer             getCompanyRoleId()       Returns the current record's "company_role_id" value
 * @method enum                getMashtab()             Returns the current record's "mashtab" value
 * @method integer             getStuffId()             Returns the current record's "stuff_id" value
 * @method integer             getUserId()              Returns the current record's "user_id" value
 * @method float               getTotal()               Returns the current record's "total" value
 * @method string              getMaturity()            Returns the current record's "maturity" value
 * @method boolean             getCompletionNotice()    Returns the current record's "completion_notice" value
 * @method integer             getPaymentDeferment()    Returns the current record's "payment_deferment" value
 * @method string              getProlongationTerm()    Returns the current record's "prolongation_term" value
 * @method date                getLaunchDate()          Returns the current record's "launch_date" value
 * @method float               getSummMonthVat()        Returns the current record's "summ_month_vat" value
 * @method float               getPlannedPf1()          Returns the current record's "planned_pf1" value
 * @method float               getPlannedPf1Percent()   Returns the current record's "planned_pf1_percent" value
 * @method city                getCity()                Returns the current record's "City" value
 * @method organization        getOrganization()        Returns the current record's "Organization" value
 * @method lookup              getDogovorType()         Returns the current record's "DogovorType" value
 * @method lookup              getCompanyRole()         Returns the current record's "CompanyRole" value
 * @method companystructure    getCompanystructure()    Returns the current record's "Companystructure" value
 * @method sfGuardUser         getUser()                Returns the current record's "User" value
 * @method stuff               getStuff()               Returns the current record's "Stuff" value
 * @method Doctrine_Collection getDopDogovor()          Returns the current record's "DopDogovor" collection
 * @method Doctrine_Collection getDogovorDepartment()   Returns the current record's "DogovorDepartment" collection
 * @method Doctrine_Collection getDogovorHandling()     Returns the current record's "DogovorHandling" collection
 * @method Dogovor             setId()                  Sets the current record's "id" value
 * @method Dogovor             setProlongation()        Sets the current record's "prolongation" value
 * @method Dogovor             setOrganizationId()      Sets the current record's "organization_id" value
 * @method Dogovor             setName()                Sets the current record's "name" value
 * @method Dogovor             setNumber()              Sets the current record's "number" value
 * @method Dogovor             setStartdatetime()       Sets the current record's "startdatetime" value
 * @method Dogovor             setStopdatetime()        Sets the current record's "stopdatetime" value
 * @method Dogovor             setCompanystructureId()  Sets the current record's "companystructure_id" value
 * @method Dogovor             setCityId()              Sets the current record's "city_id" value
 * @method Dogovor             setSubject()             Sets the current record's "subject" value
 * @method Dogovor             setFilepath()            Sets the current record's "filepath" value
 * @method Dogovor             setIsActive()            Sets the current record's "is_active" value
 * @method Dogovor             setDogovorTypeId()       Sets the current record's "dogovor_type_id" value
 * @method Dogovor             setCompanyRoleId()       Sets the current record's "company_role_id" value
 * @method Dogovor             setMashtab()             Sets the current record's "mashtab" value
 * @method Dogovor             setStuffId()             Sets the current record's "stuff_id" value
 * @method Dogovor             setUserId()              Sets the current record's "user_id" value
 * @method Dogovor             setTotal()               Sets the current record's "total" value
 * @method Dogovor             setMaturity()            Sets the current record's "maturity" value
 * @method Dogovor             setCompletionNotice()    Sets the current record's "completion_notice" value
 * @method Dogovor             setPaymentDeferment()    Sets the current record's "payment_deferment" value
 * @method Dogovor             setProlongationTerm()    Sets the current record's "prolongation_term" value
 * @method Dogovor             setLaunchDate()          Sets the current record's "launch_date" value
 * @method Dogovor             setSummMonthVat()        Sets the current record's "summ_month_vat" value
 * @method Dogovor             setPlannedPf1()          Sets the current record's "planned_pf1" value
 * @method Dogovor             setPlannedPf1Percent()   Sets the current record's "planned_pf1_percent" value
 * @method Dogovor             setCity()                Sets the current record's "City" value
 * @method Dogovor             setOrganization()        Sets the current record's "Organization" value
 * @method Dogovor             setDogovorType()         Sets the current record's "DogovorType" value
 * @method Dogovor             setCompanyRole()         Sets the current record's "CompanyRole" value
 * @method Dogovor             setCompanystructure()    Sets the current record's "Companystructure" value
 * @method Dogovor             setUser()                Sets the current record's "User" value
 * @method Dogovor             setStuff()               Sets the current record's "Stuff" value
 * @method Dogovor             setDopDogovor()          Sets the current record's "DopDogovor" collection
 * @method Dogovor             setDogovorDepartment()   Sets the current record's "DogovorDepartment" collection
 * @method Dogovor             setDogovorHandling()     Sets the current record's "DogovorHandling" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDogovor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dogovor');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('prolongation', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('startdatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('stopdatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('companystructure_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('filepath', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('dogovor_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('company_role_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mashtab', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'm_global',
              1 => 'm_local',
             ),
             ));
        $this->hasColumn('stuff_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('total', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('maturity', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('completion_notice', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('payment_deferment', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('prolongation_term', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('launch_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('summ_month_vat', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('planned_pf1', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('planned_pf1_percent', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('city as City', array(
             'local' => 'city_id',
             'foreign' => 'id'));

        $this->hasOne('organization as Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as DogovorType', array(
             'local' => 'dogovor_type_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as CompanyRole', array(
             'local' => 'company_role_id',
             'foreign' => 'id'));

        $this->hasOne('companystructure as Companystructure', array(
             'local' => 'companystructure_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('stuff as Stuff', array(
             'local' => 'stuff_id',
             'foreign' => 'id'));

        $this->hasMany('DopDogovor', array(
             'local' => 'id',
             'foreign' => 'dogovor_id'));

        $this->hasMany('DogovorDepartment', array(
             'local' => 'id',
             'foreign' => 'dogovor_id'));

        $this->hasMany('DogovorHandling', array(
             'local' => 'id',
             'foreign' => 'dogovor_id'));
    }
}