<?php

/**
 * Basestuff_departments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $stuff_id
 * @property integer $departments_id
 * @property integer $claimtype_id
 * @property string $userkey
 * @property departments $Departments
 * @property stuff $Stuff
 * @property claimtype $Claimtype
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method integer           getStuffId()        Returns the current record's "stuff_id" value
 * @method integer           getDepartmentsId()  Returns the current record's "departments_id" value
 * @method integer           getClaimtypeId()    Returns the current record's "claimtype_id" value
 * @method string            getUserkey()        Returns the current record's "userkey" value
 * @method departments       getDepartments()    Returns the current record's "Departments" value
 * @method stuff             getStuff()          Returns the current record's "Stuff" value
 * @method claimtype         getClaimtype()      Returns the current record's "Claimtype" value
 * @method stuff_departments setId()             Sets the current record's "id" value
 * @method stuff_departments setStuffId()        Sets the current record's "stuff_id" value
 * @method stuff_departments setDepartmentsId()  Sets the current record's "departments_id" value
 * @method stuff_departments setClaimtypeId()    Sets the current record's "claimtype_id" value
 * @method stuff_departments setUserkey()        Sets the current record's "userkey" value
 * @method stuff_departments setDepartments()    Sets the current record's "Departments" value
 * @method stuff_departments setStuff()          Sets the current record's "Stuff" value
 * @method stuff_departments setClaimtype()      Sets the current record's "Claimtype" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestuff_departments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stuff_departments');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('stuff_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('departments_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('claimtype_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('userkey', 'string', 25, array(
             'primary' => true,
             'type' => 'string',
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('departments as Departments', array(
             'local' => 'departments_id',
             'foreign' => 'id'));

        $this->hasOne('stuff as Stuff', array(
             'local' => 'stuff_id',
             'foreign' => 'id'));

        $this->hasOne('claimtype as Claimtype', array(
             'local' => 'claimtype_id',
             'foreign' => 'id'));
    }
}