<?php

/**
 * Basesfuff_city
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stuff_id
 * @property integer $city_id
 * @property city $Stuff
 * @property stuff $City
 * 
 * @method integer    getStuffId()  Returns the current record's "stuff_id" value
 * @method integer    getCityId()   Returns the current record's "city_id" value
 * @method city       getStuff()    Returns the current record's "Stuff" value
 * @method stuff      getCity()     Returns the current record's "City" value
 * @method sfuff_city setStuffId()  Sets the current record's "stuff_id" value
 * @method sfuff_city setCityId()   Sets the current record's "city_id" value
 * @method sfuff_city setStuff()    Sets the current record's "Stuff" value
 * @method sfuff_city setCity()     Sets the current record's "City" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesfuff_city extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sfuff_city');
        $this->hasColumn('stuff_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('city as Stuff', array(
             'local' => 'city_id',
             'foreign' => 'id'));

        $this->hasOne('stuff as City', array(
             'local' => 'stuff_id',
             'foreign' => 'id'));
    }
}