<?php

/**
 * Basestatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $stakey
 * @property string $name
 * @property integer $timereminder
 * @property string $color
 * @property string $icon
 * @property Doctrine_Collection $works
 * @property Doctrine_Collection $Claim
 * @property Doctrine_Collection $FinanceClaim
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getStakey()       Returns the current record's "stakey" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getTimereminder() Returns the current record's "timereminder" value
 * @method string              getColor()        Returns the current record's "color" value
 * @method string              getIcon()         Returns the current record's "icon" value
 * @method Doctrine_Collection getWorks()        Returns the current record's "works" collection
 * @method Doctrine_Collection getClaim()        Returns the current record's "Claim" collection
 * @method Doctrine_Collection getFinanceClaim() Returns the current record's "FinanceClaim" collection
 * @method status              setId()           Sets the current record's "id" value
 * @method status              setStakey()       Sets the current record's "stakey" value
 * @method status              setName()         Sets the current record's "name" value
 * @method status              setTimereminder() Sets the current record's "timereminder" value
 * @method status              setColor()        Sets the current record's "color" value
 * @method status              setIcon()         Sets the current record's "icon" value
 * @method status              setWorks()        Sets the current record's "works" collection
 * @method status              setClaim()        Sets the current record's "Claim" collection
 * @method status              setFinanceClaim() Sets the current record's "FinanceClaim" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('stakey', 'string', 50, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('timereminder', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('color', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
        $this->hasColumn('icon', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('works', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('claim as Claim', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('finance_claim as FinanceClaim', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}