<?php

/**
 * BaseClientOrganization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property integer $organization_id
 * @property client $Group
 * @property organization $Permission
 * 
 * @method integer            getClientId()        Returns the current record's "client_id" value
 * @method integer            getOrganizationId()  Returns the current record's "organization_id" value
 * @method client             getGroup()           Returns the current record's "Group" value
 * @method organization       getPermission()      Returns the current record's "Permission" value
 * @method ClientOrganization setClientId()        Sets the current record's "client_id" value
 * @method ClientOrganization setOrganizationId()  Sets the current record's "organization_id" value
 * @method ClientOrganization setGroup()           Sets the current record's "Group" value
 * @method ClientOrganization setPermission()      Sets the current record's "Permission" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientOrganization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_organization');
        $this->hasColumn('client_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('client as Group', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('organization as Permission', array(
             'local' => 'organization_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}