<?php

/**
 * Basehdconfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $value
 * @property string $description
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method string   getName()        Returns the current record's "name" value
 * @method string   getValue()       Returns the current record's "value" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method hdconfig setId()          Sets the current record's "id" value
 * @method hdconfig setName()        Sets the current record's "name" value
 * @method hdconfig setValue()       Sets the current record's "value" value
 * @method hdconfig setDescription() Sets the current record's "description" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basehdconfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hdconfig');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}