<?php

/**
 * BaseGroupclaimperiod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $groupclaim_id
 * @property string $period_day
 * @property string $period_month
 * @property string $period_year
 * @property Groupclaim $Groupclaim
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getGroupclaimId()  Returns the current record's "groupclaim_id" value
 * @method string           getPeriodDay()     Returns the current record's "period_day" value
 * @method string           getPeriodMonth()   Returns the current record's "period_month" value
 * @method string           getPeriodYear()    Returns the current record's "period_year" value
 * @method Groupclaim       getGroupclaim()    Returns the current record's "Groupclaim" value
 * @method Groupclaimperiod setId()            Sets the current record's "id" value
 * @method Groupclaimperiod setGroupclaimId()  Sets the current record's "groupclaim_id" value
 * @method Groupclaimperiod setPeriodDay()     Sets the current record's "period_day" value
 * @method Groupclaimperiod setPeriodMonth()   Sets the current record's "period_month" value
 * @method Groupclaimperiod setPeriodYear()    Sets the current record's "period_year" value
 * @method Groupclaimperiod setGroupclaim()    Sets the current record's "Groupclaim" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupclaimperiod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groupclaimperiod');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('groupclaim_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('period_day', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('period_month', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('period_year', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Groupclaim', array(
             'local' => 'groupclaim_id',
             'foreign' => 'id'));
    }
}