<?php

/**
 * BaseOrganizationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $title
 * @property Doctrine_Collection $organization
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getType()         Returns the current record's "type" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method Doctrine_Collection getOrganization() Returns the current record's "organization" collection
 * @method OrganizationType    setId()           Sets the current record's "id" value
 * @method OrganizationType    setType()         Sets the current record's "type" value
 * @method OrganizationType    setTitle()        Sets the current record's "title" value
 * @method OrganizationType    setOrganization() Sets the current record's "organization" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization_type');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'unique' => true,
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('organization', array(
             'local' => 'id',
             'foreign' => 'organization_type_id'));
    }
}