<?php

/**
 * BaseDepartmentPeopleMonthInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $department_people_id
 * @property integer $year
 * @property integer $month
 * @property float $surcharge
 * @property float $bonus
 * @property float $fine
 * @property integer $surcharge_type_id
 * @property integer $bonus_type_id
 * @property integer $fine_type_id
 * @property string $surcharge_type_key
 * @property string $bonus_type_key
 * @property string $fine_type_key
 * @property string $surcharge_description
 * @property string $bonus_description
 * @property string $fine_description
 * @property string $salary
 * @property integer $position_id
 * @property integer $type_id
 * @property string $type_string
 * @property integer $employment_type_id
 * @property integer $salary_type_id
 * @property boolean $is_clean_salary
 * @property integer $norma_days
 * @property integer $department_people_replacement_id
 * @property boolean $is_substitution
 * @property string $real_salary
 * @property DepartmentPeoplePosition $Position
 * @property DepartmentPeople $DepartmentPeople
 * @property DepartmentPeople $DepartmentPeopleReplacement
 * @property lookup $Type
 * @property lookup $EmploymentType
 * @property lookup $SalaryType
 * @property lookup $SurchargeType
 * @property lookup $BonusType
 * @property lookup $FineType
 * 
 * @method integer                   getDepartmentPeopleId()               Returns the current record's "department_people_id" value
 * @method integer                   getYear()                             Returns the current record's "year" value
 * @method integer                   getMonth()                            Returns the current record's "month" value
 * @method float                     getSurcharge()                        Returns the current record's "surcharge" value
 * @method float                     getBonus()                            Returns the current record's "bonus" value
 * @method float                     getFine()                             Returns the current record's "fine" value
 * @method integer                   getSurchargeTypeId()                  Returns the current record's "surcharge_type_id" value
 * @method integer                   getBonusTypeId()                      Returns the current record's "bonus_type_id" value
 * @method integer                   getFineTypeId()                       Returns the current record's "fine_type_id" value
 * @method string                    getSurchargeTypeKey()                 Returns the current record's "surcharge_type_key" value
 * @method string                    getBonusTypeKey()                     Returns the current record's "bonus_type_key" value
 * @method string                    getFineTypeKey()                      Returns the current record's "fine_type_key" value
 * @method string                    getSurchargeDescription()             Returns the current record's "surcharge_description" value
 * @method string                    getBonusDescription()                 Returns the current record's "bonus_description" value
 * @method string                    getFineDescription()                  Returns the current record's "fine_description" value
 * @method string                    getSalary()                           Returns the current record's "salary" value
 * @method integer                   getPositionId()                       Returns the current record's "position_id" value
 * @method integer                   getTypeId()                           Returns the current record's "type_id" value
 * @method string                    getTypeString()                       Returns the current record's "type_string" value
 * @method integer                   getEmploymentTypeId()                 Returns the current record's "employment_type_id" value
 * @method integer                   getSalaryTypeId()                     Returns the current record's "salary_type_id" value
 * @method boolean                   getIsCleanSalary()                    Returns the current record's "is_clean_salary" value
 * @method integer                   getNormaDays()                        Returns the current record's "norma_days" value
 * @method integer                   getDepartmentPeopleReplacementId()    Returns the current record's "department_people_replacement_id" value
 * @method boolean                   getIsSubstitution()                   Returns the current record's "is_substitution" value
 * @method string                    getRealSalary()                       Returns the current record's "real_salary" value
 * @method DepartmentPeoplePosition  getPosition()                         Returns the current record's "Position" value
 * @method DepartmentPeople          getDepartmentPeople()                 Returns the current record's "DepartmentPeople" value
 * @method DepartmentPeople          getDepartmentPeopleReplacement()      Returns the current record's "DepartmentPeopleReplacement" value
 * @method lookup                    getType()                             Returns the current record's "Type" value
 * @method lookup                    getEmploymentType()                   Returns the current record's "EmploymentType" value
 * @method lookup                    getSalaryType()                       Returns the current record's "SalaryType" value
 * @method lookup                    getSurchargeType()                    Returns the current record's "SurchargeType" value
 * @method lookup                    getBonusType()                        Returns the current record's "BonusType" value
 * @method lookup                    getFineType()                         Returns the current record's "FineType" value
 * @method DepartmentPeopleMonthInfo setDepartmentPeopleId()               Sets the current record's "department_people_id" value
 * @method DepartmentPeopleMonthInfo setYear()                             Sets the current record's "year" value
 * @method DepartmentPeopleMonthInfo setMonth()                            Sets the current record's "month" value
 * @method DepartmentPeopleMonthInfo setSurcharge()                        Sets the current record's "surcharge" value
 * @method DepartmentPeopleMonthInfo setBonus()                            Sets the current record's "bonus" value
 * @method DepartmentPeopleMonthInfo setFine()                             Sets the current record's "fine" value
 * @method DepartmentPeopleMonthInfo setSurchargeTypeId()                  Sets the current record's "surcharge_type_id" value
 * @method DepartmentPeopleMonthInfo setBonusTypeId()                      Sets the current record's "bonus_type_id" value
 * @method DepartmentPeopleMonthInfo setFineTypeId()                       Sets the current record's "fine_type_id" value
 * @method DepartmentPeopleMonthInfo setSurchargeTypeKey()                 Sets the current record's "surcharge_type_key" value
 * @method DepartmentPeopleMonthInfo setBonusTypeKey()                     Sets the current record's "bonus_type_key" value
 * @method DepartmentPeopleMonthInfo setFineTypeKey()                      Sets the current record's "fine_type_key" value
 * @method DepartmentPeopleMonthInfo setSurchargeDescription()             Sets the current record's "surcharge_description" value
 * @method DepartmentPeopleMonthInfo setBonusDescription()                 Sets the current record's "bonus_description" value
 * @method DepartmentPeopleMonthInfo setFineDescription()                  Sets the current record's "fine_description" value
 * @method DepartmentPeopleMonthInfo setSalary()                           Sets the current record's "salary" value
 * @method DepartmentPeopleMonthInfo setPositionId()                       Sets the current record's "position_id" value
 * @method DepartmentPeopleMonthInfo setTypeId()                           Sets the current record's "type_id" value
 * @method DepartmentPeopleMonthInfo setTypeString()                       Sets the current record's "type_string" value
 * @method DepartmentPeopleMonthInfo setEmploymentTypeId()                 Sets the current record's "employment_type_id" value
 * @method DepartmentPeopleMonthInfo setSalaryTypeId()                     Sets the current record's "salary_type_id" value
 * @method DepartmentPeopleMonthInfo setIsCleanSalary()                    Sets the current record's "is_clean_salary" value
 * @method DepartmentPeopleMonthInfo setNormaDays()                        Sets the current record's "norma_days" value
 * @method DepartmentPeopleMonthInfo setDepartmentPeopleReplacementId()    Sets the current record's "department_people_replacement_id" value
 * @method DepartmentPeopleMonthInfo setIsSubstitution()                   Sets the current record's "is_substitution" value
 * @method DepartmentPeopleMonthInfo setRealSalary()                       Sets the current record's "real_salary" value
 * @method DepartmentPeopleMonthInfo setPosition()                         Sets the current record's "Position" value
 * @method DepartmentPeopleMonthInfo setDepartmentPeople()                 Sets the current record's "DepartmentPeople" value
 * @method DepartmentPeopleMonthInfo setDepartmentPeopleReplacement()      Sets the current record's "DepartmentPeopleReplacement" value
 * @method DepartmentPeopleMonthInfo setType()                             Sets the current record's "Type" value
 * @method DepartmentPeopleMonthInfo setEmploymentType()                   Sets the current record's "EmploymentType" value
 * @method DepartmentPeopleMonthInfo setSalaryType()                       Sets the current record's "SalaryType" value
 * @method DepartmentPeopleMonthInfo setSurchargeType()                    Sets the current record's "SurchargeType" value
 * @method DepartmentPeopleMonthInfo setBonusType()                        Sets the current record's "BonusType" value
 * @method DepartmentPeopleMonthInfo setFineType()                         Sets the current record's "FineType" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartmentPeopleMonthInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department_people_month_info');
        $this->hasColumn('department_people_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('month', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('surcharge', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('fine', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('surcharge_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('bonus_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fine_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('surcharge_type_key', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('bonus_type_key', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('fine_type_key', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('surcharge_description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('bonus_description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('fine_description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('salary', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('position_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_string', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('employment_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('salary_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_clean_salary', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('norma_days', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('department_people_replacement_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('is_substitution', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('real_salary', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DepartmentPeoplePosition as Position', array(
             'local' => 'position_id',
             'foreign' => 'id'));

        $this->hasOne('DepartmentPeople', array(
             'local' => 'department_people_id',
             'foreign' => 'id'));

        $this->hasOne('DepartmentPeople as DepartmentPeopleReplacement', array(
             'local' => 'department_people_replacement_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as Type', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as EmploymentType', array(
             'local' => 'employment_type_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as SalaryType', array(
             'local' => 'salary_type_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as SurchargeType', array(
             'local' => 'surcharge_type_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as BonusType', array(
             'local' => 'bonus_type_id',
             'foreign' => 'id'));

        $this->hasOne('lookup as FineType', array(
             'local' => 'fine_type_id',
             'foreign' => 'id'));
    }
}