<?php

/**
 * Basecontract_works
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $works_id
 * @property integer $contract_id
 * @property contract $contract
 * @property works $works
 * 
 * @method integer        getWorksId()     Returns the current record's "works_id" value
 * @method integer        getContractId()  Returns the current record's "contract_id" value
 * @method contract       getContract()    Returns the current record's "contract" value
 * @method works          getWorks()       Returns the current record's "works" value
 * @method contract_works setWorksId()     Sets the current record's "works_id" value
 * @method contract_works setContractId()  Sets the current record's "contract_id" value
 * @method contract_works setContract()    Sets the current record's "contract" value
 * @method contract_works setWorks()       Sets the current record's "works" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecontract_works extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contract_works');
        $this->hasColumn('works_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('contract_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('contract', array(
             'local' => 'contract_id',
             'foreign' => 'id'));

        $this->hasOne('works', array(
             'local' => 'works_id',
             'foreign' => 'id'));
    }
}