<?php

/**
 * BaseGroupclaimDepartments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $groupclaim_id
 * @property integer $departments_id
 * @property Groupclaim $Groupclaim
 * @property departments $Departments
 * 
 * @method integer               getGroupclaimId()   Returns the current record's "groupclaim_id" value
 * @method integer               getDepartmentsId()  Returns the current record's "departments_id" value
 * @method Groupclaim            getGroupclaim()     Returns the current record's "Groupclaim" value
 * @method departments           getDepartments()    Returns the current record's "Departments" value
 * @method GroupclaimDepartments setGroupclaimId()   Sets the current record's "groupclaim_id" value
 * @method GroupclaimDepartments setDepartmentsId()  Sets the current record's "departments_id" value
 * @method GroupclaimDepartments setGroupclaim()     Sets the current record's "Groupclaim" value
 * @method GroupclaimDepartments setDepartments()    Sets the current record's "Departments" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupclaimDepartments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groupclaim_departments');
        $this->hasColumn('groupclaim_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('departments_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Groupclaim', array(
             'local' => 'groupclaim_id',
             'foreign' => 'id'));

        $this->hasOne('departments as Departments', array(
             'local' => 'departments_id',
             'foreign' => 'id'));
    }
}