<?php

/**
 * BaseGroupclaim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $claimtype_id
 * @property integer $groupclaimwork_id
 * @property string $formula
 * @property integer $client_id
 * @property integer $contract_importance_id
 * @property string $message
 * @property boolean $is_deleted
 * @property claimtype $Claimtype
 * @property Groupclaimwork $Groupclaimwork
 * @property Doctrine_Collection $Departments
 * @property client $Client
 * @property contract_importance $ContractImportance
 * @property Doctrine_Collection $Groupclaimperiod
 * @property Doctrine_Collection $GroupclaimDepartments
 * @property Doctrine_Collection $GroupclaimClaim
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method integer             getClaimtypeId()            Returns the current record's "claimtype_id" value
 * @method integer             getGroupclaimworkId()       Returns the current record's "groupclaimwork_id" value
 * @method string              getFormula()                Returns the current record's "formula" value
 * @method integer             getClientId()               Returns the current record's "client_id" value
 * @method integer             getContractImportanceId()   Returns the current record's "contract_importance_id" value
 * @method string              getMessage()                Returns the current record's "message" value
 * @method boolean             getIsDeleted()              Returns the current record's "is_deleted" value
 * @method claimtype           getClaimtype()              Returns the current record's "Claimtype" value
 * @method Groupclaimwork      getGroupclaimwork()         Returns the current record's "Groupclaimwork" value
 * @method Doctrine_Collection getDepartments()            Returns the current record's "Departments" collection
 * @method client              getClient()                 Returns the current record's "Client" value
 * @method contract_importance getContractImportance()     Returns the current record's "ContractImportance" value
 * @method Doctrine_Collection getGroupclaimperiod()       Returns the current record's "Groupclaimperiod" collection
 * @method Doctrine_Collection getGroupclaimDepartments()  Returns the current record's "GroupclaimDepartments" collection
 * @method Doctrine_Collection getGroupclaimClaim()        Returns the current record's "GroupclaimClaim" collection
 * @method Groupclaim          setId()                     Sets the current record's "id" value
 * @method Groupclaim          setName()                   Sets the current record's "name" value
 * @method Groupclaim          setClaimtypeId()            Sets the current record's "claimtype_id" value
 * @method Groupclaim          setGroupclaimworkId()       Sets the current record's "groupclaimwork_id" value
 * @method Groupclaim          setFormula()                Sets the current record's "formula" value
 * @method Groupclaim          setClientId()               Sets the current record's "client_id" value
 * @method Groupclaim          setContractImportanceId()   Sets the current record's "contract_importance_id" value
 * @method Groupclaim          setMessage()                Sets the current record's "message" value
 * @method Groupclaim          setIsDeleted()              Sets the current record's "is_deleted" value
 * @method Groupclaim          setClaimtype()              Sets the current record's "Claimtype" value
 * @method Groupclaim          setGroupclaimwork()         Sets the current record's "Groupclaimwork" value
 * @method Groupclaim          setDepartments()            Sets the current record's "Departments" collection
 * @method Groupclaim          setClient()                 Sets the current record's "Client" value
 * @method Groupclaim          setContractImportance()     Sets the current record's "ContractImportance" value
 * @method Groupclaim          setGroupclaimperiod()       Sets the current record's "Groupclaimperiod" collection
 * @method Groupclaim          setGroupclaimDepartments()  Sets the current record's "GroupclaimDepartments" collection
 * @method Groupclaim          setGroupclaimClaim()        Sets the current record's "GroupclaimClaim" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupclaim extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groupclaim');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('claimtype_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('groupclaimwork_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('formula', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contract_importance_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_deleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('claimtype as Claimtype', array(
             'local' => 'claimtype_id',
             'foreign' => 'id'));

        $this->hasOne('Groupclaimwork', array(
             'local' => 'groupclaimwork_id',
             'foreign' => 'id'));

        $this->hasMany('departments as Departments', array(
             'refClass' => 'GroupclaimDepartments',
             'local' => 'groupclaim_id',
             'foreign' => 'departments_id'));

        $this->hasOne('client as Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('contract_importance as ContractImportance', array(
             'local' => 'contract_importance_id',
             'foreign' => 'id'));

        $this->hasMany('Groupclaimperiod', array(
             'local' => 'id',
             'foreign' => 'groupclaim_id'));

        $this->hasMany('GroupclaimDepartments', array(
             'local' => 'id',
             'foreign' => 'groupclaim_id'));

        $this->hasMany('GroupclaimClaim', array(
             'local' => 'id',
             'foreign' => 'groupclaim_id'));
    }
}