<?php

/**
 * IdeaIdeaGoalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeaIdeaGoalTable extends PluginIdeaIdeaGoalTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdeaIdeaGoalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IdeaIdeaGoal');
    }
}