<?php

/**
 * IdeaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeaTable extends PluginIdeaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdeaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Idea');
    }

  static public function getIdeasQuery()
  {
    $query = Doctrine::getTable('Idea')
      ->createQuery('i')
      ->leftJoin('i.User u');
      //->orderBy('i.id DESC');

    return $query;
  }
}