<?php

/**
 * Idea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Idea extends PluginIdea
{
  public function getTotal()
  {
    return $this->getSignificance() + $this->getFinancial() + $this->getOriginality() + $this->getReadiness();
  }

  public function History($field = null, $toString  = null, $oldValue = null)
  {
    if (!$field||!$toString) return null;

    if (!sizeof($this->_oldValues))
    {
      return;
    }
    $history = new History();

    $history->setModelName(History::MODEL_IDEA);
    $history->setModelId($this->getId());
    $history->setFieldName($field);

    //$history->setMore();
    $history->setOldValue(isset($oldValue->_data[$field]) ? $oldValue->_data[$field] : '');
    $history->setValue($this->$toString());
    $history->save();
  }

  public function getFormattedDate()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers('Date');
    return format_date($this->getCreatedatetime(), 'dd.MM.yyyy HH:mm', 'ru');
  }

  public function getExpertDescriptionString()
  {
    return html_entity_decode($this->getExpertDescription());
  }
}
