<?php

/**
 * PluginIdeaIdeaGoalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginIdeaIdeaGoalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginIdeaIdeaGoalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginIdeaIdeaGoal');
    }
}