<?php

/**
 * PluginIdeaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginIdeaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginIdeaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginIdea');
    }
}