changepass:
  url:   /changepass
  param: { module: changepass, action: index }

messages:
  url:   /messages
  param: { module: messages, action: show } 
  
history:
  url:   /history
  param: { module: history, action: index }

add_handling:
  url:   /dogovor/add_handling/:handling_id/:dogovor_id/:organization_id
  param: { module: dogovor, action: add_handling }

update_handling_for_add:
  url:   /dogovor/update_handling_for_add/:handling_id/:dogovor_id/:organization_id
  param: { module: dogovor, action: update_handling_for_add }
  
organization:
  class: sfDoctrineRouteCollection
  options:
    model:                organization
    module:               organization
    prefix_path:          /organization
    column:               id
    with_wildcard_routes: true
  
  
# default rules
homepage:
  url:   /
  param: { module: dogovor, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }   

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
claimopened:
  url:   /claimopened
  param: { module: claimopened, action: index } 
  
claimclosed:
  url:   /claimclosed
  param: { module: claimclosed, action: index } 
  
logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout } 
  
 
  

  

