<?php

/**
 * PluginQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginQueue');
    }
}