<?php

/**
 * PluginQueueLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginQueueLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginQueueLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginQueueLog');
    }
}