<?php

/**
 * PluginModelContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginModelContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginModelContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginModelContact');
    }
}