<?php

/**
 * HistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoryTable extends PluginHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('History');
    }
    
    static public function getHistoryByIdAndModel($model_id, $model_name)
    {
      return self::getInstance()
        ->createQuery('h')
        ->where('h.model_id = ?', $model_id)
        ->addWhere('h.model_name = ?', $model_name)
        ->leftJoin('h.User u')
        ->execute();
    }
}