                <li><a href="<?php echo url_for('userclient')?>"><?php echo __('Clients')?></a></li>
                <li><a href="<?php echo url_for('userstuff')?>"><?php echo __('Staff')?></a></li>
                <li><a href="<?php echo url_for('contract')?>"><?php echo __('Contracts')?></a></li>
                <li><a href="<?php echo url_for('contract_importance')?>"><?php echo __('ContractImportance')?></a></li>
                <li><a href="<?php echo url_for('organization_importance')?>"><?php echo __('OrganizationImportance')?></a></li>
                <li><a href="<?php echo url_for('organization')?>"><?php echo __('Organization')?></a></li>
                <li><a href="<?php echo url_for('departments')?>"><?php echo __('Departments')?></a></li>
                <li><a href="<?php echo url_for('stuff_departments')?>"><?php echo __('Stuff departments')?></a></li>
                <li><a href="<?php echo url_for('dogovor')?>">Договора</a></li>
                <li><a href="<?php echo url_for('dop_dogovor')?>">Дополнительные соглашения</a></li>
                <li><a href="<?php echo url_for('widget_list')?>"><?php echo __('Widget list')?></a></li>
                <li><a href="<?php echo url_for('departments_type')?>"><?php echo __('Departments type list')?></a></li>
                <li><a href="<?php echo url_for('departments_status')?>"><?php echo __('Departments status list')?></a></li>
                <li><a href="<?php echo url_for('technical_param')?>"><?php echo __('Technical param list')?></a></li>
                <li><a href="<?php echo url_for('technical_param_type')?>"><?php echo __('Technical param type list')?></a></li>
                <li><a href="<?php echo url_for('handling_message_type')?>"><?php echo __('Handling message types')?></a></li>
                <li><a href="<?php echo url_for('handling_status')?>"><?php echo __('Handling status')?></a></li>
                <li><a href="<?php echo url_for('handling_type')?>"><?php echo __('Handling type')?></a></li>
                <li><a href="<?php echo url_for('handling_result')?>"><?php echo __('Handling result')?></a></li>
                <li><a href="<?php echo url_for('salary')?>"><?php echo __('Salary')?></a></li>
                <li><a href="<?php echo url_for('department_people_position')?>"><?php echo __('Department People Position')?></a></li>
                <li><a href="<?php echo url_for('handling_more_info_type')?>"><?php echo __('Handling more info type')?></a></li>
                <li><a href="<?php echo url_for('idea_goal')?>"><?php echo __('Idea goals')?></a></li>
