      <li><a href="<?php echo url_for('userclient')?>">Клиенты</a></li>
                <li><a href="<?php echo url_for('userstuff')?>">Сотрудники</a></li>
                      <li><a href="<?php echo url_for("organization")?>">Организация</a></li>  
                      <li><a href="<?php echo url_for("contract")?>">Контракт</a></li>  
                      <li><a href="<?php echo url_for("importance")?>">Важность</a></li>  
                      <li><a href="<?php echo url_for("contract_importance")?>">Контракт-Важность</a></li>
                      <li><a href="<?php echo url_for("contract_works")?>">Контракт-Работы</a></li>  
                      <li><a href="<?php echo url_for("workstypes")?>">ТипыРаботы</a></li>  
                      <li><a href="<?php echo url_for("works")?>">Работы</a></li>  
                      <li><a href="<?php echo url_for("departments")?>">Отделения</a></li>  
                      <li><a href="<?php echo url_for("companystructure")?>">Структура</a></li>
                      <li><a href="<?php echo url_for('stuff_departments')?>">stuff_departments</a></li>   
                      <li><a href="<?php echo url_for("city")?>">Город</a></li>
                      <li><a href="<?php echo url_for('district')?>">Район</a></li>
                      <li><a href="<?php echo url_for("region")?>">Область</a></li>  
                      
            </ul><br /><br />          
            <ul class="submenu">
                      <li><a href="<?php echo url_for("claim")?>">Заявка</a></li>
                      <li><a href="<?php echo url_for("log_claim")?>">Log Заявка</a></li>
                      <!--<li><a href="<?php echo url_for("clienttemp")?>">Клиенты</a></li>-->
                      <!--<li><a href="<?php echo url_for("stufftemp")?>">Исполнители</a></li>-->
                      <li><a href="<?php echo url_for("lookup")?>">Lookup</a></li>
                      <li><a href="<?php echo url_for("comments")?>">Коментарии</a></li>
                      <li><a href="<?php echo url_for("claimusers")?>">Claimusers</a></li>
                      <li><a href="<?php echo url_for("log_claim")?>">Log Claim</a></li>
                      <li><a href="<?php echo url_for('status')?>">Статус</a></li>
                      <li><a href="<?php echo url_for('documents')?>">documents</a></li>
                      <li><a href="<?php echo url_for('documents_claim')?>">documents_claim</a></li>
                      <li><a href="<?php echo url_for('documentstype')?>">documentstype</a></li>