<?php

/**
 * BaseTendercategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Tenderlinks
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getTenderlinks() Returns the current record's "Tenderlinks" collection
 * @method Tendercategory      setId()          Sets the current record's "id" value
 * @method Tendercategory      setName()        Sets the current record's "name" value
 * @method Tendercategory      setTenderlinks() Sets the current record's "Tenderlinks" collection
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTendercategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tendercategory');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tenderlinks', array(
             'local' => 'id',
             'foreign' => 'tendercategory_id'));
    }
}