<?php

/**
 * BaseTenderlinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $tendercategory_id
 * @property Tendercategory $Tendercategory
 * 
 * @method integer        getId()                Returns the current record's "id" value
 * @method string         getName()              Returns the current record's "name" value
 * @method integer        getTendercategoryId()  Returns the current record's "tendercategory_id" value
 * @method Tendercategory getTendercategory()    Returns the current record's "Tendercategory" value
 * @method Tenderlinks    setId()                Sets the current record's "id" value
 * @method Tenderlinks    setName()              Sets the current record's "name" value
 * @method Tenderlinks    setTendercategoryId()  Sets the current record's "tendercategory_id" value
 * @method Tenderlinks    setTendercategory()    Sets the current record's "Tendercategory" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTenderlinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tenderlinks');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('tendercategory_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tendercategory', array(
             'local' => 'tendercategory_id',
             'foreign' => 'id'));
    }
}