<?php

/**
 * BaseTenderkeywords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * 
 * @method integer        getId()   Returns the current record's "id" value
 * @method string         getName() Returns the current record's "name" value
 * @method Tenderkeywords setId()   Sets the current record's "id" value
 * @method Tenderkeywords setName() Sets the current record's "name" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTenderkeywords extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tenderkeywords');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}