<?php

/**
 * GlobalMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GlobalMessageTable extends PluginGlobalMessageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GlobalMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GlobalMessage');
    }
    
    static public function getAllMessages()
    {
      return self::getInstance()
        ->createQuery('gm')
        ->leftJoin('gm.User u')
        ->orderBy('gm.createdatetime DESC')
        ->execute();
    }
}