<?php

/**
 * GlobalMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GlobalMessage extends PluginGlobalMessage
{
  public function getCreatedatetimeGood()
  {
    return format_date($this->getCreatedatetime(), 'dd.MM.yyyy, HH:mm', 'ru');
  }
}