<?php

/**
 * BaseIdeaIdeaGoal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idea_id
 * @property integer $goal_id
 * @property Idea $Idea
 * @property IdeaGoal $Goal
 * 
 * @method integer      getIdeaId()  Returns the current record's "idea_id" value
 * @method integer      getGoalId()  Returns the current record's "goal_id" value
 * @method Idea         getIdea()    Returns the current record's "Idea" value
 * @method IdeaGoal     getGoal()    Returns the current record's "Goal" value
 * @method IdeaIdeaGoal setIdeaId()  Sets the current record's "idea_id" value
 * @method IdeaIdeaGoal setGoalId()  Sets the current record's "goal_id" value
 * @method IdeaIdeaGoal setIdea()    Sets the current record's "Idea" value
 * @method IdeaIdeaGoal setGoal()    Sets the current record's "Goal" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIdeaIdeaGoal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('idea_idea_goal');
        $this->hasColumn('idea_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('goal_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Idea', array(
             'local' => 'idea_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('IdeaGoal as Goal', array(
             'local' => 'goal_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}