generator:
  class: sfDoctrineGenerator
  param:
    model_class:           stuff_departments
    theme:                 admin
    non_verbose_templates: false
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          stuff_departments
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, stuff, departments, claimtype, userkey]
      filter:  
        display: [id, stuff_id, departments_id, claimtype_id, userkey]
      form:    ~
      edit:    ~
      new:     ~
