<?php

/**
 * TechnicalParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TechnicalParamTable extends PluginTechnicalParamTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TechnicalParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TechnicalParam');
    }
}