<?php

/**
 * TechnicalParamDepartmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TechnicalParamDepartmentsTable extends PluginTechnicalParamDepartmentsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TechnicalParamDepartmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TechnicalParamDepartments');
    }
}