ModelContact:
  package: ModelContact.
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    model_name:
      type: string(255)
      notnull: true
    model_id: 
      type: integer
    sort:
      type: integer
    first_name:
      type: string(255)
      notnull: true  
    last_name:
      type: string(255)
      notnull: true  
    middle_name:
      type: string(255)
    phone1:
      type: string(255)
      notnull: true  
    phone2:
      type: string(255)
    position:
      type: string(255)
    email:
      type: string(128)
    birthday:
      type: date
      