<?php

/**
 * BaseQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $object_model
 * @property string $object_submodel
 * @property string $object_id
 * @property string $params
 * @property timestamp $createdatetime
 * @property enum $status
 * @property integer $percent
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getObjectModel()     Returns the current record's "object_model" value
 * @method string    getObjectSubmodel()  Returns the current record's "object_submodel" value
 * @method string    getObjectId()        Returns the current record's "object_id" value
 * @method string    getParams()          Returns the current record's "params" value
 * @method timestamp getCreatedatetime()  Returns the current record's "createdatetime" value
 * @method enum      getStatus()          Returns the current record's "status" value
 * @method integer   getPercent()         Returns the current record's "percent" value
 * @method Queue     setId()              Sets the current record's "id" value
 * @method Queue     setObjectModel()     Sets the current record's "object_model" value
 * @method Queue     setObjectSubmodel()  Sets the current record's "object_submodel" value
 * @method Queue     setObjectId()        Sets the current record's "object_id" value
 * @method Queue     setParams()          Sets the current record's "params" value
 * @method Queue     setCreatedatetime()  Sets the current record's "createdatetime" value
 * @method Queue     setStatus()          Sets the current record's "status" value
 * @method Queue     setPercent()         Sets the current record's "percent" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQueue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('queue');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('object_model', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('object_submodel', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('object_id', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('createdatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'new',
              1 => 'proceed',
              2 => 'done',
             ),
             ));
        $this->hasColumn('percent', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));


        $this->index('idx_object_model_status', array(
             'fields' => 
             array(
              0 => 'object_model',
              1 => 'status',
             ),
             ));
        $this->index('idx_status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->index('idx_object_model_object_id', array(
             'fields' => 
             array(
              0 => 'object_model',
              1 => 'object_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}