<?php

/**
 * BaseQueueLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $object_model
 * @property string $object_submodel
 * @property string $params
 * @property timestamp $createdatetime
 * @property integer $user_id
 * @property enum $status
 * @property integer $persent
 * @property sfGuardUser $User
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method string      getObjectModel()     Returns the current record's "object_model" value
 * @method string      getObjectSubmodel()  Returns the current record's "object_submodel" value
 * @method string      getParams()          Returns the current record's "params" value
 * @method timestamp   getCreatedatetime()  Returns the current record's "createdatetime" value
 * @method integer     getUserId()          Returns the current record's "user_id" value
 * @method enum        getStatus()          Returns the current record's "status" value
 * @method integer     getPersent()         Returns the current record's "persent" value
 * @method sfGuardUser getUser()            Returns the current record's "User" value
 * @method QueueLog    setId()              Sets the current record's "id" value
 * @method QueueLog    setObjectModel()     Sets the current record's "object_model" value
 * @method QueueLog    setObjectSubmodel()  Sets the current record's "object_submodel" value
 * @method QueueLog    setParams()          Sets the current record's "params" value
 * @method QueueLog    setCreatedatetime()  Sets the current record's "createdatetime" value
 * @method QueueLog    setUserId()          Sets the current record's "user_id" value
 * @method QueueLog    setStatus()          Sets the current record's "status" value
 * @method QueueLog    setPersent()         Sets the current record's "persent" value
 * @method QueueLog    setUser()            Sets the current record's "User" value
 * 
 * @package    helpdesk
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQueueLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('queue_log');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('object_model', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('object_submodel', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('createdatetime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'new',
              1 => 'proceed',
              2 => 'done',
             ),
             ));
        $this->hasColumn('persent', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}