# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, style.css, jquery-ui.css, default.css]

  javascripts:    [jquery.min.js, jquery.validate.min.js, jquery.ui.min.js, jquery.dataTables.js, FixedHeader.min.js, helpdesk.js, saveClass/ManagerNew.js]

  has_layout:     true
  layout:         layout
