<?php

/**
 * PluginDocDocumentGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDocDocumentGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDocDocumentGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDocDocumentGroup');
    }
}