<?php

/**
 * PluginLogIntranetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLogIntranetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLogIntranetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLogIntranet');
    }
}