generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DopDogovor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          dop_dogovor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, dogovor, dop_dogovor_type, number, startdatetime, activedatetime, subject, is_active]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
