generator:
  class: sfDoctrineGenerator
  param:
    model_class:           departments
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          departments
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display: 
          "Main": [mpk]
          "Physical characteristics": [name]
          "Administrative characteristics": [name]
          "Persons": [name] 
      edit:    ~
      new:     ~
